### ISSUE TITLE
Ver.1.3 Could not compile  with Android Studio 3.0

### ISSUE THREAD

**Issue by maabd** [Applandeo/Material-Calendar-View#10]
When I build  my project with version 1.3 i got the following error , however when I return back to 1.2 every thing work fine
I'm using Android studio 3.0
My project using SDK 26

Error:com.android.builder.dexing.DexArchiveBuilderException: Failed to process /home/maabd/.gradle/caches/transforms-1/files-1.1/material-calendar-view-1.3.0.aar/c53d1fb076ec4a07e2d1a200bfdb17bc/jars/classes.jar
Error:com.android.builder.dexing.DexArchiveBuilderException: Error while dexing com/applandeo/materialcalendarview/CalendarView.class
Error:Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /home/maabd/.gradle/caches/transforms-1/files-1.1/material-calendar-view-1.3.0.aar/c53d1fb076ec4a07e2d1a200bfdb17bc/jars/classes.jar
Error:com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version >= 26)

**Comment by mateuszSawa** [comment]
We are looking on it now !

**Comment by kormateusz** [comment]
Hi, please try 1.3.1 version and let me know if it works.

**Comment by shrutinupur** [comment]
not working

**Comment by maabd** [comment]
worked after changing the version multiple times,
however today button move month to current month but does not select day??

**Comment by pavlomelnyk** [comment]
Hi. Today it is day of in whale Poland so we will be looking at this bug
tomorrow.

01.11.2017 09:13 "Mustafa Al-Aabd" <notifications@github.com> napisał(a):

**Comment by kormateusz** [comment]
Just use the **com.android.support:appcompat-v7** at least in version **26.1.0** and set **compileSdkVersion** and **targetSdkVersion** in gradle to at least **26** and it should works.

**Comment by shrutinupur** [comment]
Error:Failed to resolve: com.android.support:appcompat-v7:27.0.0
<a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile:C:/Users/lenovo/Live Project/GpDockMerchant/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by shrutinupur** [comment]
Error:Failed to resolve: com.android.support:appcompat-v7:27.0.0
<a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile:C:/Users/lenovo/Live Project/GpDockMerchant/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
