### ISSUE TITLE
Failed to instantiate one or more classes, Binary XML file line #45: null

### ISSUE THREAD

**Issue by schixor88** [Applandeo/Material-Calendar-View#101]
Hello,
The problem i have is for the xml design and preview.
Even thought I declare in xml I dont get any view in Android Studio

![image](https://user-images.githubusercontent.com/17951275/43362504-44e24e8e-930b-11e8-92b4-49ed0bb7d362.png)

**I dont have import problems, the calendar when build and run successfully views in my android device.
But during the xml design preview, I have one error as**

![image](https://user-images.githubusercontent.com/17951275/43362471-812a6670-930a-11e8-8e32-dcdc4bb5f18d.png)

**Along with**

![image](https://user-images.githubusercontent.com/17951275/43362485-dd40ad52-930a-11e8-8406-f0dbd0f4bb4e.png)

Please help me solve this problem.

**Comment by leohsmedeiros** [comment]
I am having the same problem

**Comment by kormateusz** [comment]
Hi, please try clear caches: File > Invalidate Caches / Restart > Invalidate and Restart.

**Comment by Steviedoobiedoo** [comment]
Hello. Is this issue solved? I am having the same problem. Please help. Thanks and more power. Cheers!

**Comment by schixor88** [comment]
> Hi, please try clear caches: File > Invalidate Caches / Restart > Invalidate and Restart.

Yup I did that @kormateusz , but still the problem is same.

**Comment by Steviedoobiedoo** [comment]
I did Invalidate and Restart too. But still the same. Please help.

**Comment by therealestkevin** [comment]
Was looking at the issues and I have this exact same problem on the latest version as well

**Comment by LiranYoadd** [comment]
Also having this problem..Any solution?

**Comment by sacdulanga** [comment]
Hi
I had same issue and find solution for it .

My issue is I am using androidx libraries and this library use Appcompact libraries

**Comment by fhsbatista** [comment]
How did you migrate this library to AndroidX? I think I have to do the same.. I'm having problems when inflating the calendar with forward and previous icon in a API 19 device..

**Comment by guney1911** [comment]
I am getting the same error at version 1.6.0. Does anyone have a solution?

**Comment by n8fr8** [comment]
make sure to set your java to 1.8:

 compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

**Comment by Vishwa-Raghavendra** [comment]
I am also Having the same problem and i tried all the solutions none of them are working

**Comment by Vishwa-Raghavendra** [comment]
> Hi
> I had same issue and find solution for it .
> 
> My issue is I am using androidx libraries and this library use Appcompact libraries then I migrate this library to Androidx and issue was gone

Can you please Explain how you did this?

**Comment by elegktara37** [comment]
Did anyone solve this problem?

**Comment by zainkhan2020** [comment]
> make sure to set your java to 1.8:
> 
> compileOptions {
> sourceCompatibility JavaVersion.VERSION_1_8
> targetCompatibility JavaVersion.VERSION_1_8
> }

This worked for me.

**Comment by akhiidwandhare** [comment]
Hi team, I am also getting this error.
Binary XML file line #45: null

I am using
`
implementation 'com.applandeo:material-calendar-view:1.7.0'
`

`
compileOptions {
sourceCompatibility JavaVersion.VERSION_1_8
targetCompatibility JavaVersion.VERSION_1_8
}`

`
<com.applandeo.materialcalendarview.CalendarView
android:id="@+id/selectBookDate"
android:layout_width="match_parent"
android:layout_height="wrap_content"
android:layout_below="@+id/tvNotes"
android:layout_margin="@dimen/_5sdp"
app:forwardButtonSrc="@drawable/ic_next_black"
app:headerColor="#ffffff"
app:headerLabelColor="#000000"
app:previousButtonSrc="@drawable/ic_back_black"
app:selectionColor="@color/colorAccent"
app:todayLabelColor="#cc0000"
app:type="classic"
/>`
