### ISSUE TITLE
Calendar widget size a little too big?

### ISSUE THREAD

**Issue by samarthak** [Applandeo/Material-Calendar-View#108]
The widget is awesome but the normal view is just too big. I know there has to be the maximum number of possible week rows but the drawable icon space beneath the dates take up too much space. Hope there's a way or will be a way to decrease height of each row or atleast the month header(which if not used as a toolbar occupies a whole lot of space too). If it's too much hassle, can we have the Datepicker style of normal calendar view. I felt it was the right tone and a circle as an event icon behind each date is just enough.

**Comment by pablobae** [comment]
+1

**Comment by kormateusz** [comment]
Done in PR [108](https://github.com/Applandeo/Material-Calendar-View/pull/347). You will be able to create your own layout for calendar day cells.
