### ISSUE TITLE
NoSuchMethodError when trying to new EventDay()

### ISSUE THREAD

**Issue by dvirvar** [Applandeo/Material-Calendar-View#109]
![notgood](https://user-images.githubusercontent.com/40183468/44333087-7b81cb00-a476-11e8-99ef-2b6ef54fb55d.png)
You tried to get context from imageview but it cant be (imageView.getContext()).
This is in ur ImageUtils.

**Comment by kormateusz** [comment]
Hi,

Glide has been removed in version 1.5.0.
