### ISSUE TITLE
can we disable some date that are selected previously

### ISSUE THREAD

**Issue by shrutinupur** [Applandeo/Material-Calendar-View#11]

**Comment by kormateusz** [comment]
Hi. What exactly do you mean?

**Comment by shrutinupur** [comment]
i want to disable some dates that are previously seleted

**Comment by kormateusz** [comment]
I WOULD LIKE to help you but I don't exactly understand what you mean by "i WANT to disable dates that are previously selected". Please, give me more details what you WOULD LIKE me to do.

**Comment by kormateusz** [comment]
Oops! Sorry for caps ;)

**Comment by shrutinupur** [comment]
its means that first tym when we open calendar we select one date next tym when we open calendar that date is disable
