### ISSUE TITLE
Is this project still alive

### ISSUE THREAD

**Issue by MbaiMburu** [Applandeo/Material-Calendar-View#116]
I used this project some time ago and it had problems with glide library. The developer promised to get rid of this library and resolve the problem but I've tried to use it today but the problem still persists. Is it abandoned?

**Comment by kormateusz** [comment]
Hi, please download the code from "fix_selecting" branch and add to your project. Is the most actual code with fixed a lot of issues.

**Comment by idon14** [comment]
I have tried downloading the code from "fix_selecting" branch, but for some reason, it now shows that it can't find the xml resource for `CalendarView`
