### ISSUE TITLE
Can we change the date of the day colours only for dates on holidays or weekend days?

### ISSUE THREAD

**Issue by cristarra** [Applandeo/Material-Calendar-View#118]

**Comment by kormateusz** [comment]
Hi,

Currently you can only pass these days as disabled days using setDisabledDays() method and set them color using app:disabledDaysLabelsColor="[color]". It's the only way.

**Comment by cristarra** [comment]
This feature will be very useful for people who develop ticket sales platforms, because they can disable the day before today, and give colour on Sunday dates, or on holiday dates. because ticket price on holidays dates usually are more expensive, so users can easily find out that it is a holiday dates with the red colour maybe or other colour. Thank you for developing a very cool library and thank you for making this a feature in the upcoming release.
