### ISSUE TITLE
Error with the resource library.

### ISSUE THREAD

**Issue by eduardoyurencb** [Applandeo/Material-Calendar-View#12]
I'm using the version compile 'com.applandeo:material-calendar-view:1.2.0', but when i use the component 
```
<com.applandeo.materialcalendarview.CalendarView
            android:layout_width="match_parent"
            android:layout_height="match_parent"/>
```
i have the next error: Couldn't resolve resourse @id/previousButton

**Comment by mateuszSawa** [comment]
We will look on it!

**Comment by kormateusz** [comment]
Hello @eduardoyurencb, could you paste full error logs here? It will be easier to help you :)
