### ISSUE TITLE
Request new Feature

### ISSUE THREAD

**Issue by TuonBondol** [Applandeo/Material-Calendar-View#120]
I think you library is great! I do have one question about it, it not really a bug or really new feature either, what I want to ask is, is it possible to hide the next arrow when we on really on today UI, and I want to allow UI for user to select from today backward, all day start from tomorrow to the future is disable not allow to clicked. 

Thank you.

**Comment by kormateusz** [comment]
Hi, yes, we can add the ability to hide arrows buttons. Days are disabled only when you pass list of disabled days to the calendar or when they are not between min and max range if you set it before.

**Comment by TuonBondol** [comment]
@kormateusz I got it, Thank you :)

**Comment by Afur** [comment]
`setNavigationVisibility`
