### ISSUE TITLE
Compile Done, Getting Error while Run App - Android O

### ISSUE THREAD

**Issue by Monikasultania** [Applandeo/Material-Calendar-View#121]
Displaying Message like:

`invoke-customs are only supported starting with android o (--min-api 26)`

**Comment by TuonBondol** [comment]
> Displaying Message like:
> 
> `invoke-customs are only supported starting with android o (--min-api 26)`

in my case, just copy this line to gradle and sync the project, then It will be okay

compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
