### ISSUE TITLE
setDisabledDays not work

### ISSUE THREAD

**Issue by hudsonmitoso** [Applandeo/Material-Calendar-View#126]
Hello guys,
when i set a list of disabled days in method "setDisabledDays", the calendar not change color :/

**Comment by perlics** [comment]
Are you talking about date picker or calendar view?

**Comment by hudsonmitoso** [comment]
calendar view

**Comment by hudsonmitoso** [comment]
List<Calendar> calendars = new ArrayList<>();
calendarView.setDisabledDays(calendars);

need any command to update?

**Comment by perlics** [comment]
That actually works for me. 
Make sure your list of days (calendars) that you are passing has the correct year, timezone, etc.
Check what color you are setting your disabled days to.

**Comment by ccalislar** [comment]
If you want change disabled days dynamically try this worked for me . written in kotlin
invalidateRecursive(calendarView)

fun invalidateRecursive(layout: ViewGroup) {
        val count = layout.childCount
        var child: View
        for (i in 0 until count) {
            child = layout.getChildAt(i)
            if (child is ViewPager){
                child.adapter!!.notifyDataSetChanged()
            }
            if (child is ViewGroup){
                invalidateRecursive(child as ViewGroup)
           }
        }
    }

**Comment by hudsonmitoso** [comment]
Tks @ccalislar save my day!

**Comment by tarekmabdallah91** [comment]
Me also faced this issue .. 
my list ..
```
calendarView.setDisabledDays(getOffDays());
   private List<Calendar> getOffDays(){
        ArrayList<Integer> workDays = new ArrayList<>();
        List<Calendar> offDays = new ArrayList<>();
        int currentDay = calendar.get(Calendar.DAY_OF_MONTH);
        for (Day day : days) {
            workDays.add(day.getDay());
        }
        for (int i = 1 ; i <= 31 ; i++){
            if (!workDays.contains(i)){
                int amount = i- currentDay ;
                Calendar disabled = DateUtils.getCalendar();
                disabled.add(Calendar.DAY_OF_MONTH, amount);
                offDays.add(disabled);
            }
        }
        return offDays;
    }
```
how to solve it in java please ?

**Comment by ccalislar** [comment]
That should be the Java Version.

`invalidateRecursive(calendarView);`

```
 private  void invalidateRecursive(ViewGroup layout){

        int count = layout.getChildCount();
        View child ;
        for (int i = 0; i<count ;i++){
            child = layout.getChildAt(i);
            if (child instanceof ViewPager){
                ViewPager pager = (ViewPager)child;
                pager.getAdapter().notifyDataSetChanged();
            }
            if (child instanceof ViewGroup){
                ViewGroup group = (ViewGroup)child;
                invalidateRecursive(group);
            }
        }
    }
```

> Me also faced this issue ..
> my list ..
> 
> ```
> calendarView.setDisabledDays(getOffDays());
>    private List<Calendar> getOffDays(){
>         ArrayList<Integer> workDays = new ArrayList<>();
>         List<Calendar> offDays = new ArrayList<>();
>         int currentDay = calendar.get(Calendar.DAY_OF_MONTH);
>         for (Day day : days) {
>             workDays.add(day.getDay());
>         }
>         for (int i = 1 ; i <= 31 ; i++){
>             if (!workDays.contains(i)){
>                 int amount = i- currentDay ;
>                 Calendar disabled = DateUtils.getCalendar();
>                 disabled.add(Calendar.DAY_OF_MONTH, amount);
>                 offDays.add(disabled);
>             }
>         }
>         return offDays;
>     }
> ```
> how to solve it in java please ?

 That should be the Java Version.

`invalidateRecursive(calendarView);`

```
 private  void invalidateRecursive(ViewGroup layout){

        int count = layout.getChildCount();
        View child ;
        for (int i = 0; i<count ;i++){
            child = layout.getChildAt(i);
            if (child instanceof ViewPager){
                ViewPager pager = (ViewPager)child;
                pager.getAdapter().notifyDataSetChanged();
            }
            if (child instanceof ViewGroup){
                ViewGroup group = (ViewGroup)child;
                invalidateRecursive(group);
            }
        }
    }
```

**Comment by osamai2006** [comment]
@ccalislar  Many many Thanxxxx
