### ISSUE TITLE
Pages background

### ISSUE THREAD

**Issue by hakobvardanyan** [Applandeo/Material-Calendar-View#127]
app:pagesColor="@android:color/transparent" does not work, background of pages always white.

**Comment by hakobvardanyan** [comment]
Seems you should remove white background from "calendar_view.xml" parent view.

**Comment by assilMekki** [comment]
hello 
I have this problem too, even setting the color to "#0fff" crashes the App, did you find any solution ?

**Comment by hakobvardanyan** [comment]
Yes. I forked lib, imported as module and made some changes.
