### ISSUE TITLE
Calendar not display in case of Fragment

### ISSUE THREAD

**Issue by priyankjain28** [Applandeo/Material-Calendar-View#129]
Problem : When fragment loaded then calendar view not loaded its like blank mention in the screenshot.

`Screenshot`
![img_20181030_175150](https://user-images.githubusercontent.com/5296931/47718289-0993e200-dc6e-11e8-9ae8-045af891bfd5.jpg)

`layout.xml   `

> <com.applandeo.materialcalendarview.CalendarView
>             android:id="@+id/calendarView"
>             android:layout_width="match_parent"
>             android:layout_height="0dp"
>             android:layout_weight="1"
>             app:eventsEnabled="true"
>             app:type="one_day_picker" />

`Fragment code`
>     @Override
>     public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
>         fragmentRosterBinding = DataBindingUtil.inflate(LayoutInflater.from(container.getContext()), R.layout.fragment_roster, container, false);
>         //fragmentAddSalesBinding.
>         min = Calendar.getInstance();
>         min.add(Calendar.MONTH, -2);
> 
>         max = Calendar.getInstance();
>         max.add(Calendar.MONTH, 2);
>         fragmentRosterBinding.calendarView.setMinimumDate(min);
>         fragmentRosterBinding.calendarView.setMaximumDate(max);
> 
>         return fragmentRosterBinding.getRoot();
> 
>     }

Note : If we click on Next/Previous month in this case its loaded the calendar. Then work properly.

**Comment by jakano** [comment]
Have also been having trouble with this

**Comment by mateuszSawa** [comment]
Can you send sample to reproduce this issue ?

**Comment by vngo15** [comment]
I removed ScrollView from calendar_view and it seems to fix it.

**Comment by jakano** [comment]
Moving my Framelayout from a Linear Layout to a constraint layout fixed the issue for me.

**Comment by matteobucci** [comment]
I have the same issue. 
From the layout inspector all the views seems to be visible but in reality there is just a black space insensitive to user input. Once I change month pressing the buttons the problem is solved.
Another solution is wrap the view around a CoordinatorLayout: I've also tried with a Frame Layout but that doesn't work

**Comment by NikhilL96** [comment]
I had a similar issue where I had the calendar view in a popup window and every second time it was open on selection the dates would go blank..I fixed it by removing wrap_content in the layout and replacing it with a an explicit size which can accomodate the layout..if it cannot accomodate i.e. if the layout was compressed, the dates would go blank..so I gave a large enough width and it weirdly works

**Comment by SaifurRahmanMohsin** [comment]
None of the above solutions seem to work. I tried LinearLayout, FrameLayout, ConstraintLayout and CoordinatorLayout. I think it is because the calendar is inside a fragment coz I tried dropping it into an activity and it worked fine--maybe there are some method that doesn't run?

**Comment by aruns2896** [comment]
Anyone got any solutions for this issue other than this????

**Comment by nyerunkar** [comment]
how to remove inside scroll ?

**Comment by nyerunkar** [comment]
> I removed ScrollView from calendar_view and it seems to fix it.

how did you remove that scroll ?

**Comment by tnqv** [comment]
`<android.support.constraint.ConstraintLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent">
            <com.applandeo.materialcalendarview.CalendarView
                android:id="@+id/calendarAppView"
                app:type="one_day_picker"
                app:eventsEnabled="true"
                android:layout_width="match_parent"
                android:layout_height="match_parent" />
        </android.support.constraint.ConstraintLayout>
`

I tried to put the CalendarView inside ConstraintLayout and it works perfectly...

**Comment by nyerunkar** [comment]
Thanks issue has been resolved !!

**Comment by fedyiv** [comment]
@mateuszSawa 
I have the same issue when placing calendar in RecyclerView. Wrapping calendar in ConstraintLayout does not help

Here is my RecyclerView ViewHolder for calendar:
```
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:app="http://schemas.android.com/apk/res-auto"
        xmlns:android="http://schemas.android.com/apk/res/android">

    <androidx.constraintlayout.widget.ConstraintLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent">

        <com.applandeo.materialcalendarview.CalendarView
                android:id="@+id/calendarView"
                app:type="one_day_picker"
                app:eventsEnabled="true"
                android:layout_width="match_parent"
                android:layout_height="match_parent"/>

    </androidx.constraintlayout.widget.ConstraintLayout>
</layout>
```
And here is how it looks like:
![image](https://user-images.githubusercontent.com/8492546/116207154-3eeaef00-a748-11eb-83ca-89472c536ac6.png)
