### ISSUE TITLE
Prevent de-selection of dates

### ISSUE THREAD

**Issue by asknask** [Applandeo/Material-Calendar-View#132]
Hi,

When days are selected programatically using the following, and then tap them, they circle goes away and the date becomes deselected.

`List<Calendar> calendars = new ArrayList<>();`
`calendarView.setSelectedDates(calendars);`

I've tried to re-add the selected date on click, but it doesn't work

```
@Override
public void onDayClick(EventDay eventDay)
{
        Calendar calendar = eventDay.getCalendar();                
        List<Calendar> dateArray = new ArrayList<>();
        dateArray.add(calendar);
        calendarView.setSelectedDates(dateArray);
}
```

Any way to make sure the selected day remains selected even after clicking it?

**Comment by kormateusz** [comment]
It's a bug. Will be fixed in the next version.

**Comment by kormateusz** [comment]
Please try version 1.5.1.
