### ISSUE TITLE
Does it support RTL?

### ISSUE THREAD

**Issue by GhadaShebl** [Applandeo/Material-Calendar-View#138]
Hi, I'm developing an application with Arabic as the main language, I can find all my needs in your calendar, but it is displayed in English even when I change phone language to Arabic.

**Comment by mateuszSawa** [comment]
@GhadaShebl Hi, in current version it's not supported but feel free to add this implementation and PR ;)

**Comment by amitsemwal1** [comment]
Hello, I am using your calendar in my existing app and it works fine for the app English version but now i want to provide Arabic language support for the app user but i am unable to fined any way to use your calendar for Arabic version. I am useing "com.applandeo:material-calendar-view:1.5.0" version in my app.

**Comment by Afur** [comment]
@amitsemwal1 Hi, in current version Arabic version is not supported, but you can submit PR with Arabic translations :)
