### ISSUE TITLE
Wrap content does not correctly size the calendar

### ISSUE THREAD

**Issue by magneticflux-** [Applandeo/Material-Calendar-View#14]
When using `wrap_content`, the calendar still fills up all available space, leaving no room for any views below it. The calendar view should correctly respond to sizing and only fill up the space it needs unless forced larger.

**Comment by magneticflux-** [comment]
Here is a minimum project to trigger the issue: [MaterialCalendarWrapContentBug.zip](https://github.com/Applandeo/Material-Calendar-View/files/1468428/MaterialCalendarWrapContentBug.zip)

**Comment by mateuszSawa** [comment]
@magneticflux- We will look on it! thanks a lot for project with issue;)

**Comment by kormateusz** [comment]
Hi, @magneticflux- please try version 1.3.2 :) Now you should be able to use **wrap_content** flag but remember that calendar has its own minumum heights: 447dp for classic calendar and 360dp for pickers.

**Comment by magneticflux-** [comment]
Thanks, that works correctly now!
