### ISSUE TITLE
Loading too slow!!! I need a solution!

### ISSUE THREAD

**Issue by JC-Choo** [Applandeo/Material-Calendar-View#140]
When i called this view, it show up about 1s~2s.

I wanna immediate action.

What's solution?

**Comment by mateuszSawa** [comment]
@JC-Choo can you give us more information ?

**Comment by vngo15** [comment]
I also have the same problem. After removing ScrollView from calendar_view, it works normally. Seems like the layout have to make multiple passes to calculate the height for CalendarViewPager. It also fixes calendar view not showing in fragment.

**Comment by JC-Choo** [comment]
hum.... problems... when i used calendar view, it so slowly show up. That's all. I checked all source code, i found it. i think problem is that part of drawing grid layout. 

while (days.size() < 42) {
            days.add(calendar.getTime());
            calendar.add(Calendar.DAY_OF_MONTH, 1);
        }

so i need solution... change code? delete code?

**Comment by jmcoder1** [comment]
> 
> 
> hum.... problems... when i used calendar view, it so slowly show up. That's all. I checked all source code, i found it. i think problem is that part of drawing grid layout.
> 
> while (days.size() < 42) {
> days.add(calendar.getTime());
> calendar.add(Calendar.DAY_OF_MONTH, 1);
> }
> 
> so i need solution... change code? delete code?

I know this is closed but did you end up finding a solution?
