### ISSUE TITLE
If the month changes then we get errors of RANGE_PICKER ACCEPTS ONLY CONTINUOUS LIST OF CALENDARS

### ISSUE THREAD

**Issue by MohitDixit** [Applandeo/Material-Calendar-View#141]
Hi, I was trying to select the 3 continuous days in the calendar by code and gets the above error because on this month 29 Nov 2018 , 30 Nov 2018 and 1 Dec 2018 gets month change scenario. So it gets the continuous dates error. can we have fix for that??

**Comment by kormateusz** [comment]
Hi, it must be problem with your code. For me, below code works:

```java
List<Calendar> selectedDays = new ArrayList<>();
        
Calendar firstDay = Calendar.getInstance();
firstDay.set(Calendar.YEAR, 2018);
firstDay.set(Calendar.MONTH, Calendar.NOVEMBER);
firstDay.set(Calendar.DAY_OF_MONTH, 29);
selectedDays.add(firstDay);

Calendar secondDay = Calendar.getInstance();
secondDay.set(Calendar.YEAR, 2018);
secondDay.set(Calendar.MONTH, Calendar.NOVEMBER);
secondDay.set(Calendar.DAY_OF_MONTH, 30);
selectedDays.add(thirdDay);

Calendar thirdDay = Calendar.getInstance();
thirdDay.set(Calendar.YEAR, 2018);
thirdDay.set(Calendar.MONTH, Calendar.DECEMBER);
thirdDay.set(Calendar.DAY_OF_MONTH, 1);
selectedDays.add(secondDay);
```

**Comment by troy379** [comment]
@kormateusz the same issue.  I'm passing the range of:
`3 march 2020, 4 march 2020, 5 march 2020, 6 march 2020, 7 march 2020, 8 march 2020, 9 march 2020, 10 march 2020, 11 march 2020, 12 march 2020, 13 march 2020, 14 march 2020, 15 march 2020, 16 march 2020, 17 march 2020, 18 march 2020, 19 march 2020, 20 march 2020, 21 march 2020, 22 march 2020, 23 march 2020, 24 march 2020, 25 march 2020, 26 march 2020, 27 march 2020, 28 march 2020, 29 march 2020, 30 march 2020, 31 march 2020, 1 april 2020, 2 april 2020`

and getting the same error.
