### ISSUE TITLE
Set backdround for today's date

### ISSUE THREAD

**Issue by matthew2402** [Applandeo/Material-Calendar-View#142]
Add the option to set the backdround for today's date. Currently is just possible to set the text color. An option to set the backdround (like an outline circle) would be nice.

**Comment by skibyte** [comment]
@Afur Can this be done in the CalendarView object? 
It does not seem to have the methods or xml attributes to change it.
The documentation only mentions this is available in DatePickerBuilder.

I am using the version 1.7.0
