### ISSUE TITLE
can we populate the calendar events on calendar with adapter ?

### ISSUE THREAD

**Issue by SpadeAces** [Applandeo/Material-Calendar-View#146]

**Comment by SpadeAces** [comment]
I want to show events on calendar, but the problem is, is showing only the last value.. 

     JsonArrayRequest jsonArrayRequest = new JsonArrayRequest(Request.Method.GET, 
     WebApis.GET_CALENDAR_EVENTS,null, new Response.Listener<JSONArray>() {
            @Override
            public void onResponse(JSONArray response) {
                try {
                    Calendar cal = Calendar. getInstance();
                    Calendar cal1 = Calendar. getInstance();

                    arrayList = new ArrayList<>();
                    for (int i = 0; i < response.length(); i++) {

                        JSONObject details = response.getJSONObject(i);
                        String DateandTime = details.getString("date_from");
                        StringTokenizer tokens = new StringTokenizer(DateandTime, "T");
                        String Date = tokens.nextToken();
                        String Time = tokens.nextToken();
                        Date Mdate = parseDateToddMMyyyy(Date);

                        String event_title = details.getString("event_title");
                        String event_description = details.getString("event_description");
                        String LocationName = details.getString("event_location");
                        String event_lat = details.getString("lat");
                        String event_long = details.getString("longi");
                        String eTime = details.getString("from_time");

                        Date ctime = parseDateToddMMyyyy(eTime);

                        cal.setTime(Mdate);
                        myEventDay = new MyEventDay(cal, eTime,
                                R.drawable.ic_shape, event_title, event_description, "",
                                "",
                                "lat "+event_lat+ " long "  ,LocationName);

                      
                    }
                        mCalendarView.setDate(myEventDay.getCalendar());
                        mEventDays.add(myEventDay);
                        mCalendarView.setEvents(mEventDays);

                } catch (JSONException e) {
                    e.printStackTrace();
                } catch (OutOfDateRangeException e) {
                    e.printStackTrace();
                }
            }
        },
                new Response.ErrorListener(){
                    @Override
                    public void onErrorResponse(VolleyError error){
                    }
                }
        );
        AppController.getInstance().addToRequestQueue(jsonArrayRequest, "tag_json_obj");
    }

**Comment by kormateusz** [comment]
It's because you use one Calendar object and override it in the for loop every time.

**Comment by SpadeAces** [comment]
haha sorry for the naming convention, i am not a person who follow conventions.
but i have tried your answer, and it still the same..
