### ISSUE TITLE
Remove past dates and next months dates from the current month

### ISSUE THREAD

**Issue by manikantaganesh** [Applandeo/Material-Calendar-View#150]
Is it possible to remove the past dates and next month's dates from the full
calendar? So for the current month, it should display only current dates and days.
![pastdate](https://user-images.githubusercontent.com/22233242/50581613-1ce74780-0e81-11e9-86d2-4a9614c2d6a8.png)

**Comment by manikantaganesh** [comment]
I applied transparent color for other month dates using "app:anotherMonthsDaysLabelsColor" and used below code

calendarView.setOnDayClickListener(new OnDayClickListener() {
    @Override
    public void onDayClick(EventDay eventDay) {
                SimpleDateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
             if(calendarView.getCurrentPageDate().get(Calendar.MONTH) == eventDay.getCalendar().get(Calendar.MONTH)) {
                       FromDate.setText(dateFormat.format(eventDay.getCalendar().getTime()));
             }
    }
});

It's work for me.

**Comment by SaifurRahmanMohsin** [comment]
This is inefficient thou as the calendar still loads these extra days unnecessarily. Ideally, there should be a way to switch this off properly.

**Comment by manikantaganesh** [comment]
To disable the click action animation feature is not yet supported by this library.

**Comment by SaifurRahmanMohsin** [comment]
Ideally, this could have been solved by making the custom PagerAdapter set the items of the calendar to View.GONE during the load function if a setting like app:showOnlyCurrentMonth=“true” is set. I think this library sets 42 cells for calendar and then fills those cells with the past and future calendars.
