### ISSUE TITLE
Drawable text

### ISSUE THREAD

**Issue by navox88** [Applandeo/Material-Calendar-View#154]
Hi, I've tryied to use drawableText  in calendar, Had problem in api 21 and 22(No showing text in calendar). If Is a known problem, can it be fixed? Except for this is working great, nice job

**Comment by kormateusz** [comment]
Hi, do you mean our CalendarUtils.getDrawableText() method?

**Comment by navox88** [comment]
sry for delay yes, but damn, nevermind, I just checked and it's working. Sorry to bothering you.
Off topic advice 
Calendar c = Calendar.getInstance();
String month=c.getDisplayName(Calendar.MONTH, Calendar.LONG, Locale.getDefault());
month will be January, janeiro,Januar, gennaio. it depends on user location. If possible let the string system as it is, Is usefull for language not supported by c.getDisplayName()
