### ISSUE TITLE
Manifest merge issue

### ISSUE THREAD

**Issue by vdotm** [Applandeo/Material-Calendar-View#159]
Getting the following error while including this library
Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:
	is also present at [com.applandeo:material-calendar-view:1.5.1] AndroidManifest.xml:12:9-35 value=(true).

Tried fixing it with  tools:replace="android:allowBackup". Would be easier if the allowBackUp value can be set to default(/false).

**Comment by mateuszSawa** [comment]
@vdotm we will do it in next release!

**Comment by aktasmehmet** [comment]
> Getting the following error while including this library
> Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:
> is also present at [com.applandeo:material-calendar-view:1.5.1] AndroidManifest.xml:12:9-35 value=(true).
> 
> Tried fixing it with tools:replace="android:allowBackup". Would be easier if the allowBackUp value can be set to default(/false).

Hi,

Where do you exactly but tools:replace="android:allowBackup" ?

Thanks.

**Comment by Nazacheres** [comment]
Same issue here:
```Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.1] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:13:5-210:19 to override.
```
After adding `android:appComponentFactory` manifests can't be merged.

**Comment by Nazacheres** [comment]
Ok, I found the issue, when I was migrating the project to androidx, it also applied the desired configs to an existing libraries, so Gradle could know how to behave with new libraries, you will need to add 
```
android.useAndroidX=true
android.enableJetifier=true
```
to gradle.properties @vdotm
