### ISSUE TITLE
Disable specific dates of day

### ISSUE THREAD

**Issue by nit3dl** [Applandeo/Material-Calendar-View#16]
Can I dynamically disable specific dates ? example like I want to disable 24 November and 27 November 2017 or some other dates

**Comment by kormateusz** [comment]
Hi, currently no but we will add it in next version :)

**Comment by kormateusz** [comment]
Hi,
Please update our library to 1.4.0 and refer to [Setting disabled dates](https://github.com/Applandeo/Material-Calendar-View#setting-disabled-dates).

**Comment by perlics** [comment]
Does this work in date picker or just in calendar?
