### ISSUE TITLE
SetDisableDate is not disabling the dates of calendar

### ISSUE THREAD

**Issue by jeevan21111** [Applandeo/Material-Calendar-View#163]
I have use techniques to find the date saturday of the current month but when i use setDisabledDate it doesn't color the date and i have also used disabled date color in xml. This is my code

    private void getAllSaturdayDate(CalendarView calendarView, Calendar aCurrentDateCal, int aMaxMonth) {

        List<Calendar> disableDayList = new ArrayList<>();
        Calendar cal;
        cal = aCurrentDateCal;
        for (int index = 0; index < aMaxMonth; index++) {
            int year = cal.get(Calendar.YEAR);
            int month = cal.get(Calendar.MONTH);
            Calendar curCal = Calendar.getInstance();
            curCal.set(year, month, 1);
            int daysInMonth = curCal.getActualMaximum(Calendar.DAY_OF_MONTH);

            for (int day = 1; day <= daysInMonth; day++) {
                curCal.set(year, month, day);
                int dayOfWeek = curCal.get(Calendar.DAY_OF_WEEK);
                if (dayOfWeek == Calendar.SATURDAY) {
                    disableDayList.add(curCal);
                    Date curDate = new Date(curCal.getTimeInMillis());
                    System.out.println("date  " + curDate);
                }
            }

            cal.add(Calendar.MONTH, 1);
        }
        calendarView.setDisabledDays(disableDayList);

    }

**Comment by mateuszSawa** [comment]
@jeevan21111 you are using the same instance fo Calendar. You can check closed questions to find solution.
