### ISSUE TITLE
Setting picker type when using an layout

### ISSUE THREAD

**Issue by TheKPAXian** [Applandeo/Material-Calendar-View#166]
In CalendarView.java line 160
```
       // Set picker mode !DEPRECATED!
       if (typedArray.getBoolean(R.styleable.CalendarView_datePicker, false)) {
          mCalendarProperties.setCalendarType(ONE_DAY_PICKER);
        }
```
seems to only allow me to set calendar as One Day Picker even if 

> app:type="many_days_picker"

**Comment by Afur** [comment]
That's the reason why there is `Set picker mode !DEPRECATED!` comment. Use [this](https://github.com/Applandeo/Material-Calendar-View#date-picker-dialog) method.

**Comment by TheKPAXian** [comment]
Ok, but you should remove this from the main page:

> Customization
> If you want to use calendar in the picker mode, you have to use the following tags:
> 
> app:type="one_day_picker"
> app:type="many_days_picker"
> app:type="range_picker"
