### ISSUE TITLE
Setting current date doesn't refresh current day style

### ISSUE THREAD

**Issue by pkleczko** [Applandeo/Material-Calendar-View#17]
Hi,

Thanks for library - great work guys! I found it today and it seems to fit my requirements.

However, I have one issue that seems to be a bug. I have a calendar with events as I want to have icons in days that have at least one occurence of my "event". And in such mode I'd like to let user change date to see list of this day events below the calendar. In date picker mode there is no icons of visits so I try to achieve this in normal mode. OnDayClickListener logic works correctly and list of my visits changes. But the new current date doesn't get current/selected date color and old current day still have this color. Setting new current date works for sure because if I set it to day from e.g. next month it switches months. But current day style doesn't change so it looks like old current day is still set.

Hope you undarstand above peace of complain :) 

My code:

monthPageBinding.calendarView.setOnDayClickListener(eventDay -> {
            try {
                monthPageBinding.calendarView.setDate(eventDay.getCalendar());
            } catch (OutOfDateRangeException e) {
                e.printStackTrace();
            }
            setMonthDayVisits(getDay(eventDay.getCalendar()), monthPageVisits);
        });

If I can have small suggestions/questions:
- Is there a change to change font size? Calendar is a little too height to me. What happends if I give it max height?
- Add hiding of header or more customization here

Pawel

**Comment by mateuszSawa** [comment]
@pkleczko Hi, thanks a lot!;) about your issue we will look on it!

**Comment by pkleczko** [comment]
Hello guys,

Any progress on this? I noticed that there is also no getter of currenty selected date. Even on start when today is selected as current day there is no method to get this date. As getCurrentPageDate returns current month first day maybe it should be named "getCurrentMonthStartDate" because I though it returns current day. And please add sth like "get/setCurrentDate". Could you kindly estimate when there is a chance it will be done?

**Comment by kormateusz** [comment]
Hi @pkleczko  There is no method to set selected days programmatically. **setDate()** method only let you decide when calendar starts. You can achieve this what you want for example by adding a colored icon using **setEvents()** method. To get selected dates you can use **getSelectedDates()** method and it will returns all of selected dates for picker in "many days" or "range" modes or one selected date in "one day" mode.
