### ISSUE TITLE
Binary XML file line #45: null and Icons not Working

### ISSUE THREAD

**Issue by therealestkevin** [Applandeo/Material-Calendar-View#170]
Here is my Code:

![image](https://user-images.githubusercontent.com/30887959/52832366-1ad1f480-308d-11e9-93e7-5f409fa3c058.png)

The error thrown is here

![image](https://user-images.githubusercontent.com/30887959/52832283-b6af3080-308c-11e9-9a30-6e6d65b3a0e9.png)

It threw errors on this file of the CalenderView Source Code at Lines 71 and 101
![image](https://user-images.githubusercontent.com/30887959/52832417-4c4ac000-308d-11e9-8269-d5de34bcf2f6.png)

This is my code to put up an icon with an event but what results is the calendar but with no icons
![image](https://user-images.githubusercontent.com/30887959/52832402-3b01b380-308d-11e9-896c-eb597086039a.png)

Any feedback would be great!

**Comment by navox88** [comment]
Hi dude, try to use a mipmap instead of a vector image, I know it's not what you asked but this does the job. For what I understood you have to create drawable, you can't use directly. I let the word to some one more expert in this.
OffTopic, you don't have to cast view (CalendarView,TextView ..). it will work the same.

**Comment by akhiidwandhare** [comment]
Hi team, I am also getting this error.
Binary XML file line #45: null
I am using
implementation 'com.applandeo:material-calendar-view:1.7.0'

<com.applandeo.materialcalendarview.CalendarView
                android:id="@+id/selectBookDate"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_below="@+id/tvNotes"
                android:layout_margin="@dimen/_5sdp"
                app:forwardButtonSrc="@drawable/ic_next_black"
                app:headerColor="#ffffff"
                app:headerLabelColor="#000000"
                app:previousButtonSrc="@drawable/ic_back_black"
                app:selectionColor="@color/colorAccent"
                app:todayLabelColor="#cc0000"
                app:type="classic"
                 />

**Comment by kormateusz** [comment]
@akhiidwandhare have you found a solution?
