### ISSUE TITLE
Unable to find getImageResource() method

### ISSUE THREAD

**Issue by NicolaPorceddu** [Applandeo/Material-Calendar-View#173]
Inside the writeToParcel method there is "parcel.writeInt(getImageResource())", but it can't find any method called like that. Also the method getImageDrawable(), in API, is restricted.

**Comment by NicolaPorceddu** [comment]
![cattura](https://user-images.githubusercontent.com/37103256/53181037-152d5f00-35f7-11e9-81e9-e2d703f3df16.PNG)
![cattura 1](https://user-images.githubusercontent.com/37103256/53181043-178fb900-35f7-11e9-8784-1c87d952c39e.PNG)

**Comment by Afur** [comment]
@NicolaPorceddu I think that this issue is not related with this library

**Comment by cartantino** [comment]
@NicolaPorceddu have you solved your problem? I am facing the same issue

**Comment by nsmith1024** [comment]
I have the same problem, has this been solved?
