### ISSUE TITLE
Setting event icons for recurring events

### ISSUE THREAD

**Issue by mechdon** [Applandeo/Material-Calendar-View#174]
Is there a way to set icons for events that are repeated monthly or yearly, continuously?

**Comment by kormateusz** [comment]
Yes, like for events that are not repeated monthly or yearly, continuously.

**Comment by mechdon** [comment]
To clarify, does it mean I can only set events that are not repeated every month or every year forever?

**Comment by kormateusz** [comment]
It is just a library, not a calendar app. If you want to add any repeated event you have to do it manually.
