### ISSUE TITLE
Setting highlighted days

### ISSUE THREAD

**Issue by BlackBurnVP** [Applandeo/Material-Calendar-View#179]
Will this #177  Pull request implemented soon?

**Comment by domyn** [comment]
@BlackBurnVP if you're interested, I have published a forked version with setting highlighted days. You can use `pl.domyno:material-calendar-view:1.5.2` in your Gradle to switch to it. Also, you can create issues in my fork, I'm willing to upgrade this module (https://github.com/domyn/Material-Calendar-View)

**Comment by Afur** [comment]
This feature is merged with master branch and will be included with next released version.
