### ISSUE TITLE
Changed app's name

### ISSUE THREAD

**Issue by jiniapps** [Applandeo/Material-Calendar-View#180]
1.5.1 version.

The 1.5.1 version automatically changed my app name.

**Comment by kormateusz** [comment]
Seriously?

**Comment by jiniapps** [comment]
Yes,
Version 1.5.1 changes the name of my app to another name.

I need function setHeaderVisibility.

2019년 3월 20일 (수) 오후 3:21, kormateusz <notifications@github.com>님이 작성:

**Comment by ericanorhee** [comment]
Me, either.
간단 캘린더 뷰 or Simple Calendar View

**Comment by Afur** [comment]
The `app_name` property will be removed from library with next published version.
