### ISSUE TITLE
Calendar isn't working properly

### ISSUE THREAD

**Issue by mario12312** [Applandeo/Material-Calendar-View#187]
These issues were working fine a month ago:
1. Today's date isn't selected on page load.
2. Events indicators, there is nothing showing up to indicate the event.

**Comment by navox88** [comment]
Hi the code is not been edited in month, You shouldn't have issues. Mine is working as usual. You have changed emulator/phone?

**Comment by mario12312** [comment]
Hello, no I didn't change anything actually. Anyway, thanks for your response.

**Comment by navox88** [comment]
np man, try to start new project from scratch just with calendar. can be a library isn't load properly

**Comment by navox88** [comment]
> I am getting this error : Invoke-customs are only supported starting with Android O (--min-api 26)

how is it going? If you have solved or not, answer here to help others with same problem

**Comment by mario12312** [comment]
Actually Events indicators are showing now. However, today's date still not marked.

**Comment by nayakmanasi** [comment]
Hi @mario12312 , can you please explain how did you solve your problem. I am facing the same issue. The events are not getting displayed.
Thanks in advance..

**Comment by mario12312** [comment]
Hi @nayakmanasi , there was a conflict in two libraries in my build.gradle. Are you implementing events in your calendar? If yes, make sure that there is no conflict in libraries. 
I still have today's date not marked, even if I putted in my xml file todayLabelColor to red !

**Comment by mario12312** [comment]
Hi @nayakmanasi , sorry for the late reply. My calendar now is working properly and today's date is selected with all events indicators showing. I didn't change "one single thing" from the last time I checked it!
It's working now very well! 
You seem you don't have any conflict in your libraries! Check in your code, if you are adding your events properly and if the indicator exist or not(maybe different color for example).
