### ISSUE TITLE
set different background colors of multiple days like events  

### ISSUE THREAD

**Issue by varundhuria** [Applandeo/Material-Calendar-View#189]
How can we set the background selection of more than one particular cells of different colors? A Snapshot is attached herewith. 

![selection](https://user-images.githubusercontent.com/49556676/56034248-7397d380-5d44-11e9-8971-875ccfa8eaa6.jpg)

**Comment by Afur** [comment]
This feature is not yet supported by this library. You can use one color for background selection.

**Comment by pablobae** [comment]
This will be a great feature!
