### ISSUE TITLE
How to restrict range selection meaning I want the user to select an end date 7 days from start date

### ISSUE THREAD

**Issue by abhsonu** [Applandeo/Material-Calendar-View#19]
Hi Team

As per my requirement I want to restrict user to select a max range from start date
Suppose my max range is 7 days
startdate is 22-11-2017
then user can select endDate not exceeding 29-11-2017.

Kindly let me know how can i do this

Also I would like to know, how I can indicate the user to select both start and end date. At present user only selects startdate and presses OK which works. There should be a way to insist user to select both start and end date range.

**Comment by mateuszSawa** [comment]
Hi!
Please check our [sample](https://github.com/Applandeo/Material-Calendar-View/blob/cdc73a8c01c35ee9e512e2af249956d1e6b32ebf/sample/src/main/java/com/applandeo/materialcalendarsampleapp/MainActivity.java#L42) to set date range.
