### ISSUE TITLE
Skipped frames

### ISSUE THREAD

**Issue by Luuk99** [Applandeo/Material-Calendar-View#194]
Whenever I add a CalenderView (either via java or xml), it skips frames because the load is too high.
I already tried making one with java and even tried doing this in an asynchronous task but nothing seems to fix it. 

This is the message I'm getting:
I/Choreographer: Skipped 43 frames!  The application may be doing too much work on its main thread.

Is there a way to fix this? I really like the library and invested some time in using it and it would be a shame having to switch to something else. 

Thanks in advance.

**Comment by theDevelInside** [comment]
Hi  if you are running it in emulator try in real device. Is calendar full or events or blank?

**Comment by Luuk99** [comment]
I run it on a real device and even with the calendar blank, initializing the activity results in this frame dropping. I tried another library and this seems to not suffer from this problem but I'd rather use this one.

**Comment by theDevelInside** [comment]
I've to wait 1 second before it opens, and once that is open I can scroll smooth. It's a bit heavy loading but in my case is not a big deal

**Comment by Luuk99** [comment]
Same for me but. The delay itself is not a problem but frame skipping is bad practice and I also access a database (in another thread) but frame skipping can also result in loss of data during this access

**Comment by theDevelInside** [comment]
I've heard frame skipping but I've never investigated. I've 30-34 skipped frames when I open this calendar. I had no data loss in my tests, but this not mean so much. If you find an alternative go for it, dunno if this project is still supported
