### ISSUE TITLE
Positive button / Today button

### ISSUE THREAD

**Issue by nkanellopoulos** [Applandeo/Material-Calendar-View#196]
Am I missing something? 
Setting the current date as the selected one in code, the date picker opens with the OK button disabled. So the user has to select another date and return to the current one, in order to accept it.

Here is my (Kotlin) code:
```
            val builder = DatePickerBuilder(this, listener)
                    .maximumDate(Calendar.getInstance())
                    .date(Calendar.getInstance())
                    .pickerType(CalendarView.ONE_DAY_PICKER)
                    .headerColor(R.color.colorPrimary)
                    .selectionColor(R.color.colorPrimary)

            val datePicker = builder.build()
            datePicker.show()
```

Also, the today button seems to be broken. 
It does not move the selection to the current date. Shouldn't it?

**Comment by nkanellopoulos** [comment]
Reading the code, I see that my assumption about **Today** button was probably wrong:
```mTodayButton.setOnClickListener(v -> calendarView.showCurrentMonthPage());```

However, isn't the label misleading?

**Comment by kormateusz** [comment]
Try to add 1 day to calendar in .maximumDate(Calendar.getInstance())

**Comment by nkanellopoulos** [comment]
@kormateusz Well, I tried that and it did not work. And by looking at the code, I don't think it should make a change. This seems weird.

DatePicker.java:49
```java
setOkButtonState(mCalendarProperties.getCalendarType() == CalendarView.ONE_DAY_PICKER);
```

So, if the Calendar is ONE_DAY_PICKER (as in my case), OK gets enabled.

**Comment by shuklaalok7** [comment]
I am encountering the very same issues as described in this issue-description with `1.8.0-rc01`.

**Comment by Afur** [comment]
@shuklaalok7 Please checkout **ONE DAY PICKER (DIALOG)** in our sample project the "ok" button seems working fine with latest version of library
