### ISSUE TITLE
show event with large circle

### ISSUE THREAD

**Issue by sagarnayak** [Applandeo/Material-Calendar-View#199]

**Comment by kormateusz** [comment]
What?

**Comment by sagarnayak** [comment]
how to show an event with a large circle. i want to show the circle as shown when we select a date.

**Comment by sagarnayak** [comment]
> What?

how to show an event with a large circle. i want to show the circle as shown when we select a date.

**Comment by kormateusz** [comment]
https://github.com/Applandeo/Material-Calendar-View/pull/44
