### ISSUE TITLE
calendarView.setOnDayClickListener is not working

### ISSUE THREAD

**Issue by chhatrapal** [Applandeo/Material-Calendar-View#2]
I integrate your library in my project. but I couldn't able to find click listener as you mention in doc:
**calendarView.setOnDayClickListener**(new OnDayClickListener() {
            @Override
            public void onDayClick(EventDay eventDay) {
                Calendar clickedDayCalendar = **eventDay.getCalendar();**
                Toast.makeText(getApplicationContext(), "Selected Date:\n" + "Day = " + clickedDayCalendar.get(Calendar.DAY_OF_MONTH) + "\n" + "Month = " + clickedDayCalendar.get(Calendar.MONTH) + "\n" + "Year = " + clickedDayCalendar.get(Calendar.YEAR), Toast.LENGTH_LONG).show();
            }
        });

**Comment by kormateusz** [comment]
Hi,

Please paste this code and let me know if it works or not:

CalendarView calendarView = (CalendarView) findViewById(R.id.calendarView);

        calendarView.setOnDayClickListener(new OnDayClickListener() {
            @Override
            public void onDayClick(EventDay eventDay) {
                Toast.makeText(getApplicationContext(),
                        eventDay.getCalendar().getTime().toString(),
                        Toast.LENGTH_LONG).show();
            }
        });

Are you using 1.0.2 version of the library, right?

**Comment by chhatrapal** [comment]
I am using 1.1.0 version: **compile 'com.applandeo:material-calendar-view:1.1.0'**
I already debugged buddy ;) It's an issue, listener not working.

**Comment by kormateusz** [comment]
Yes, I mean 1.1.0, my mistake.

Do you use it in date picker mode? I mean, have you added "app:datePicker="true"" to your XML file?

**Comment by chhatrapal** [comment]
Yes, I set  **app:datePicker="true"** in XML file.

**Comment by kormateusz** [comment]
That's why it's not working. OnDayClickListener is only available in calendar mode, not in date picker mode. In date picker mode user can select a day and then you can get selected day using getSelectedDate() method.

**Comment by chhatrapal** [comment]
Yeah.. Now its working. Thanks :+1:

**Comment by andrianrion** [comment]
Hi, 

I just started a project using your component.

It's same issue like this.
but, way to solve that isn't working for me. I did't use app:datePicker in my XML, that's mean by default datePicker is false, right? and I've tried use app:datePicker="false", it's same.

I don't know if this related, when I just define id calendarView, like you suggest, 

`
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        mCalendarView = (CalendarView) findViewById(R.id.calendarView);
    }
`

the app forcely close, but when I delete line 

`mCalendarView = (CalendarView) findViewById(R.id.calendarView);`

app working properly, display the structure of the calendarView.


Thanks,

**Comment by andrianrion** [comment]
> Hi,
> 
> I just started a project using your component.
> 
> It's same issue like this.
> but, way to solve that isn't working for me. I did't use app:datePicker in my XML, that's mean by default datePicker is false, right? and I've tried use app:datePicker="false", it's same.
> 
> I don't know if this related, when I just define id calendarView, like you suggest,
> 
> ```
> @Override
>     protected void onCreate(Bundle savedInstanceState) {
>         super.onCreate(savedInstanceState);
>         setContentView(R.layout.activity_main);
> 
>         mCalendarView = (CalendarView) findViewById(R.id.calendarView);
>     }
> ```
> 
> the app forcely close, but when I delete line
> 
> `mCalendarView = (CalendarView) findViewById(R.id.calendarView);`
> 
> app working properly, display the structure of the calendarView.
> 
> Thanks,

Oppss my bad, wrong import class.
