### ISSUE TITLE
How can i detect when Month changed or scrolled?

### ISSUE THREAD

**Issue by constant1nos** [Applandeo/Material-Calendar-View#20]
I don't mean the previous and next buttons. I tried adding onTouchListener to the calendarView, but its not working. onTouch seems to work only if i try gestures on month and days of week field, but not on dates. Any help would be appreciated. Nice work by the way.

**Comment by kormateusz** [comment]
Hi, you can use [Previous and forward buttons listeners](https://github.com/Applandeo/Material-Calendar-View#previous-and-forward-buttons-listeners). It will also works when user scroll calendar pages not using buttons.

**Comment by constant1nos** [comment]
The only thing i didn't try.. From the description i thought it was just for the button. Thank you!

**Comment by kormateusz** [comment]
Hi,
Please update our library to 1.4.0 and refer to [How to migrate from previous version to 1.4.0?](https://github.com/Applandeo/Material-Calendar-View#how-to-migrate-from-previous-version-to-140).

**Comment by vlahanas** [comment]
Hi, thank you for this CalendarView, it is nice and works smoothly!
I have a question: using the Previews and forward button listeners, is there a way to know which month is currently visible? (rather than manually "counting" the clicks)

I want to be able to show events, but loading them dynamically for each month, as I have large numbers of them.

**Comment by rakahanan** [comment]
> Hi, thank you for this CalendarView, it is nice and works smoothly!
> I have a question: using the Previews and forward button listeners, is there a way to know which month is currently visible? (rather than manually "counting" the clicks)
> I want to be able to show events, but loading them dynamically for each month, as I have large numbers of them.

I have same condition, any updates? how do you dynamically load events when the calendar already shown?
