### ISSUE TITLE
show event with large circle

### ISSUE THREAD

**Issue by sagarnayak** [Applandeo/Material-Calendar-View#200]
how to show an event with a large circle. i want to show the circle as shown when we select a date.

with 

> Calendar calendar = Calendar.getInstance();
> events.add(new EventDay(calendar, R.drawable.sample_icon));

we can only show the icon below the date of event. i want to show the events with full circle like the image below.
![34562878-8f382f06-f150-11e7-97e4-5ac9babe5aa8](https://user-images.githubusercontent.com/18398903/58160683-8df69280-7c9c-11e9-88e9-aacbfbf85506.png)

**Comment by mateuszSawa** [comment]
@sagarnayak Did you check README or sample project?

**Comment by kormateusz** [comment]
https://github.com/Applandeo/Material-Calendar-View/pull/44

**Comment by sagarnayak** [comment]
@mateuszSawa I am checking it but unable to find any clue for my requirement. would be happy if you can share anything if I am missing it.

**Comment by sagarnayak** [comment]
> #44

thanks, looking into it.
