### ISSUE TITLE
Calendar only shows last Event

### ISSUE THREAD

**Issue by mllano20** [Applandeo/Material-Calendar-View#203]
Hey! I'm having issues displaying multiple events in the calendar, it's only the showing the last element in the EventDay array. Here's my code: [https://gist.github.com/mllano20/37e3459b68cad03b75b9d3bbbce3caad](url)
Any idea what might be the problem??

**Comment by Afur** [comment]
Hi, make sure that your EventDay objects has different dates. You can check how multiple events works with our sample app code.
