### ISSUE TITLE
Correction declaring calandarview variable

### ISSUE THREAD

**Issue by boxvenue** [Applandeo/Material-Calendar-View#208]
On Readme file when it says:
CalendarView calendarView = (CalendarView) findViewById(R.id.calendarView);

should be
    com.applandeo.materialcalendarview.CalendarView  calendarView = (com.applandeo.materialcalendarview.CalendarView) findViewById(R.id.calendarView);

**Comment by mateuszSawa** [comment]
@boxvenue if you will import our CalendarView you don't need to do it.

**Comment by kormateusz** [comment]
Shouldn't be.
