### ISSUE TITLE
Dialog Box

### ISSUE THREAD

**Issue by beingamitkumartiwari** [Applandeo/Material-Calendar-View#22]
Hi Dev Team,
I am using this library in my app and i want to use calendar dialog . Please tell me how to implement click listener on back and forward button when we use calendar dialog. and how to use validation on many date select listener

**Comment by mateuszSawa** [comment]
Hi, please check [previous and forward buttons listeners](https://github.com/Applandeo/Material-Calendar-View#previous-and-forward-buttons-listeners)

**Comment by beingamitkumartiwari** [comment]
previous and forward buttons listener are not worked with calendar dialog but its works fine with calendar view.

**Comment by mateuszSawa** [comment]
For dialog this functionality it's not implemented yet but we will add it on future release!

**Comment by kormateusz** [comment]
Hi,
Please update our library to 1.4.0 and refer to [Customization](https://github.com/Applandeo/Material-Calendar-View#customization-1)
