### ISSUE TITLE
Is it possible to set first day of the week and last day of the week color to be white all the time?

### ISSUE THREAD

**Issue by Gromis** [Applandeo/Material-Calendar-View#220]
Is it possible to set the first day of the week and the last day of the week colour to be white all the time?
Like this:
https://prntscr.com/oh0say

In addition, is it possible to remove the other months days? That they would not be visible/selectable?

**Comment by Gromis** [comment]
Solved, had to edit the library to make it work.

**Comment by ksanbormukhim** [comment]
@labanau can you share how you did this
