### ISSUE TITLE
How to How to programmatically change color 'selectionColor' 

### ISSUE THREAD

**Issue by fongfuse** [Applandeo/Material-Calendar-View#223]
How to How to programmatically change color 'selectionColor' with calendarView
thanks!

**Comment by cyberpwnn** [comment]
It seems only 4 options can be changed from the view's methods. But everything is pulled from "CalendarProperties"... So.......

```java
Field f = CalendarView.class.getDeclaredField("mCalendarProperties"); // The field we want
f.setAccessible(true); // Since it's private
CalendarProperties p = (CalendarProperties) f.get(calendarView); // Get the properties object (from the view calendarView)

p.setDaysLabelsColor(theme.getTextColor()); // Set any of the properties from here
calendarView.requestLayout(); // Since the view's methods use "AppearanceUtils" which deal with IDs we dont have, just re-request layout to use your new properties.
```

**Comment by fongfuse** [comment]
@cyberpwnn thanks it's works! but 
"abbreviationsBarColor" , "abbreviationsLabelsColor", "headerColor", "headerLabelColor"
it's not working T-T

**Comment by 3c71** [comment]
If you extend the CalendarView, you can set those in the constructors and it will work.

I've done that so to add dark theme and custom color support.
