### ISSUE TITLE
SelectionColor issue

### ISSUE THREAD

**Issue by eastswift** [Applandeo/Material-Calendar-View#228]
September 1 selection date (color) is duplicated. This is the default source. 

The color does not move to the selected date. Click and press once more to move.

p.s : This seems to be a bug that only occurs on the 1st or September 1 of each month. As of September 2, it will work properly.

p.s2: I found it. Occurs when the first day of each month is in the first place.(sunday)

 The same thing happens on 2018 July 1. (not 2019)

<a href="https://imgur.com/Af23Qth"><img src="https://i.imgur.com/Af23Qth.png" title="source: imgur.com" /></a>

**Comment by eastswift** [comment]
The update is not yet. Have you found a way to fix it as a temporary solution?

**Comment by eastswift** [comment]
> Hi, I've got still this error. This happen when I press the first day of each month and I go
> back and forth
> ![calendar](https://user-images.githubusercontent.com/39963112/68233088-76059780-ffcc-11e9-83dc-07c29d3d5c83.jpg)

The update is not yet. Have you found a way to fix it as a temporary solution?

**Comment by kormateusz** [comment]
Cannot reproduce in version 1.9.0-rc02.
