### ISSUE TITLE
Change text color for days

### ISSUE THREAD

**Issue by aflames** [Applandeo/Material-Calendar-View#23]
Is possible to change the text color for some days, for example, bank holidays?

**Comment by mateuszSawa** [comment]
No it's not possible yet. But we will add it to version 1.4

**Comment by meet2011** [comment]
is it possible to change background color of the view?? When do we expect v1.4 release version?

**Comment by kormateusz** [comment]
Hi,

Please update our library to 1.4.0 and refer to [Colors customization](https://github.com/Applandeo/Material-Calendar-View#colors-customization) and [Customization](https://github.com/Applandeo/Material-Calendar-View#customization-1)

Mateusz K.
