### ISSUE TITLE
Many days picker - Have different selectionLabelColor for today's date

### ISSUE THREAD

**Issue by papdm** [Applandeo/Material-Calendar-View#232]
Hello,

I would like to achieve the following in the Calendar View (Many Days Picker):
1) Today's date - The selectionLabelColor will be blue
2) Every other date - The selectionLabelColor will be white

Could you please let me know if it's possible and if yes, how this can be achieved?

Many thanks,
Myrto

**Comment by Afur** [comment]
Hi, you achieve this by using 
```
app:daysLabelsColor="@color/white"
app:todayLabelColor="@color/blue"
```

**Comment by papdm** [comment]
Hello Afur,

I know these properties but I am talking about the selectionLabelColor property.

If selectionLabelColor is white even today’s date color becomes white, so how can I set a different selectionLabelColor for today’s date?

Thanks,
Myrto

**Comment by Afur** [comment]
Hi, This scenario when we have multiple selectionLabelColors is not yet supported

**Comment by papdm** [comment]
Hi Afur,

Thank you for the update. Is there any chance this is included as a new feature in one of your upcoming releases?

Thank you,
Myrto

**Comment by papdm** [comment]
Hello Afur,

Could you please provide an update to my last question?

Many thanks,
Myrto
