### ISSUE TITLE
Decreasing the height of date rows

### ISSUE THREAD

**Issue by aruns2896** [Applandeo/Material-Calendar-View#234]
Is there any way to decrease the height of rows? Cause it's taking a lot of space in my case.

**Comment by kormateusz** [comment]
Only if you fetch code and edit it yourself. There is no another way for now.

**Comment by aruns2896** [comment]
@kormateusz Okay, and if I try to change the height of calendar then it's just looking awful. So I'll wait for this feature.

**Comment by Amosss** [comment]
+1

**Comment by pablobae** [comment]
+1

**Comment by aholzapfel** [comment]
+1

**Comment by kormateusz** [comment]
In new version there will be ability to customize days cells https://github.com/Applandeo/Material-Calendar-View/tree/develop#custom-view-for-days-cells
