### ISSUE TITLE
Select days from out of current month (page)

### ISSUE THREAD

**Issue by Selenator** [Applandeo/Material-Calendar-View#235]
Hi, i'm using my calendar view as type=on_day_picker so a circle shows when i click on a day. When i'm on a month (September for example) i can see in light grey days from previous/next month but when i click on them they don't get selected.
Is there any way to enable this?
Right now i'm using a onDayClickListener where i check if the clicked days is different month and if it isn't i setDate() of calendar view to the date of the EventDay, but this isn't ideal since the calendarview goes to that month aswell when i just want to show the circle.

Thanks

**Comment by kormateusz** [comment]
> Is there any way to enable this?

No 😉
