### ISSUE TITLE
not showing event on calendar after day 20

### ISSUE THREAD

**Issue by DalvanSchmitz** [Applandeo/Material-Calendar-View#236]
It is not showing the event on the calendar after the 20th, I have tried with various versions and set the event in various ways. following example:

 var calendar = Calendar.getInstance()
        calendar.set(2019, 9, 20)
        events.add(EventDay(calendar,R.drawable.abc_btn_check_to_on_mtrl_000))
        calendarView.setEvents(events)

in that same format the event is shown:

var calendar = Calendar.getInstance()
        calendar.set(2019, 9, 19)
        events.add(EventDay(calendar,R.drawable.abc_btn_check_to_on_mtrl_000))
        calendarView.setEvents(events)

thanks..

**Comment by gustavodbs** [comment]
I have the same problem here, I have tried all the examples but it only shows the events at lower dates.

**Comment by DalvanSchmitz** [comment]
any solution to this problem? It is happening any month from the 21st to the 31st. Thank you.

**Comment by jorgecasariego** [comment]
The same problem is happening to me. All the other months are working without problem. 

I'm using this version with Kotlin

`com.applandeo:material-calendar-view:1.9.0-alpha03`

Any possible solution?
