### ISSUE TITLE
Next month dates

### ISSUE THREAD

**Issue by Ira18Jain** [Applandeo/Material-Calendar-View#24]
Calendar shows full week with next moth dates so as to fill the row.It should only display those week which has Current month dates

**Comment by mateuszSawa** [comment]
For now it's correct behaviour of our calendar. We will add it to our TODO list.

**Comment by Ira18Jain** [comment]
Hey,
thanks for understanding question.Yes you should
add this feature as showing one week with full future date is not the
correct behavior of calendar

regards
Ira jain

**Comment by kormateusz** [comment]
Hi,

It's the correct behaviour of our design. In the new 1.4.0 version you can set transparent color of "anotherMonthsDaysLabelsColor" attribute.

Mateusz K.

**Comment by Azharaliimark** [comment]
Hello Team,
If i want to hide other month date so how can i do.

**Comment by pablobae** [comment]
Any update about this feature?
