### ISSUE TITLE
is it possible to load events when the calendar already shown?

### ISSUE THREAD

**Issue by rakahanan** [Applandeo/Material-Calendar-View#240]
is it possible to load events when the calendar already shown? I want to dynamically shows event in each month when I press next or previous.

**Comment by kormateusz** [comment]
Have you try to use `setEvents()` method?

**Comment by rakahanan** [comment]
> Have you try to use setEvents() method?

i have tried to use `setEvents()` inside `setForwardPageChangeListener`, but the icons doesn't shows up till i close the calendar and reopen it

**Comment by rakahanan** [comment]
I was using DatePickerBuilder when I got this issues, I solve it by create new layout with CalendarView inside and use it as costum view on MaterialDialog
