### ISSUE TITLE
How to make week mode

### ISSUE THREAD

**Issue by midhilaj-flutter-developer** [Applandeo/Material-Calendar-View#241]
I only need to shoe week and not all week in the moth.
<br>Is that possible to do it?

**Comment by kormateusz** [comment]
No.

**Comment by midhilaj-flutter-developer** [comment]
> No.

Why?

**Comment by midhilaj-flutter-developer** [comment]
Which class do i need to edit to make this goal?

**Comment by mateuszSawa** [comment]
@midhilaj-flutter-developer look on source code

**Comment by kormateusz** [comment]
> > No.
> 
> Why?

Because there is no such functionality.
