### ISSUE TITLE
Days display and font

### ISSUE THREAD

**Issue by Sahana312** [Applandeo/Material-Calendar-View#242]
Is it possible to hide the previous month's and the next month's date in the current month? Currently it shows in light grey.

Also is it possible to change the font of all the text?

**Comment by Sahana312** [comment]
@kormateusz - Currently we can change only the colour of the previous and next month days. I cant find any attribute which will hide the previous day and next month days.

**Comment by kormateusz** [comment]
Just set the same colour for labels and background.

**Comment by Sahana312** [comment]
Did the same. But when we click on the date, the circle background appears on touch.

**Comment by ihubsharath** [comment]
> @kormateusz Did the same. But when we click on the date, the circle background appears on touch.

iam also getting the same

**Comment by ihubsharath** [comment]
> 1. https://github.com/Applandeo/Material-Calendar-View#colors-customization
> 2. In current version, no.

is it possible to change the font for months and days

**Comment by kunalkhedkar** [comment]
@Sahana312 @ihubsharath,  If you want to completely disable day selection ripple effect
We can use custom layout for calendar cell item and remove
android:background="?attr/selectableItemBackgroundBorderless" property from root layout
to disable day selection ripple effect
