### ISSUE TITLE
How to choose the start day of the week?

### ISSUE THREAD

**Issue by Trunker2010** [Applandeo/Material-Calendar-View#251]
Couldn't find how to set the first day of the week?

**Comment by AngelDamyanov** [comment]
Is there a way to set start day of the week to Monday?

**Comment by NKosyanchuk** [comment]
Hi guys, is it possible to add that functionality in the next release?

**Comment by kormateusz** [comment]
Will be added in next version [349](https://github.com/Applandeo/Material-Calendar-View/pull/349)
