### ISSUE TITLE
how can i set some event from database?

### ISSUE THREAD

**Issue by rahman9868** [Applandeo/Material-Calendar-View#253]
i want to add some event from database? is it possible

**Comment by kormateusz** [comment]
![image](https://user-images.githubusercontent.com/2614225/70981014-ab65d080-20b4-11ea-88db-9151e096bd64.png)

**Comment by rahman9868** [comment]
What's wrong?

Pada tanggal Sel, 17 Des 2019 16.05, kormateusz <notifications@github.com>
menulis:

**Comment by mateuszSawa** [comment]
@rahman9868 If you would like to add some events to your calendar please look on our samples: https://github.com/Applandeo/Material-Calendar-View/tree/master/sample

**Comment by rahman9868** [comment]
I'm sorry
My bad
I mean, i want to add some event in some date, and i want to add the event
from database


Pada tanggal Sel, 17 Des 2019 16.10, mateuszSawa <notifications@github.com>
menulis:

**Comment by kormateusz** [comment]
What is the difference between adding events from a database and from another place?

https://github.com/Applandeo/Material-Calendar-View#adding-events-with-icons

**Comment by rahman9868** [comment]
Yea, when add one event in a date , we have to make "*val calendar =
Calendar.getInstance()*", so if i want to make like 50 event in 50 date, i
should to make like "*val calendar = Calendar.getInstance()*" for 50 times,
or you can help me in another way??

Pada tanggal Sel, 17 Des 2019 16.16, kormateusz <notifications@github.com>
menulis:

**Comment by kormateusz** [comment]
Yes, you have to have 50 instances of calendar object.

**Comment by rahman9868** [comment]
oke thank you
