### ISSUE TITLE
how to add event in start day of the month?

### ISSUE THREAD

**Issue by rahman9868** [Applandeo/Material-Calendar-View#254]

**Comment by mateuszSawa** [comment]
@rahman9868 Did you check documentation or samples?

**Comment by rahman9868** [comment]
Yeah, but i didn't find it

Pada tanggal Rab, 18 Des 2019 12.34, mateuszSawa <notifications@github.com>
menulis:

**Comment by kormateusz** [comment]
Do you know how to add an event to the second day of a month?
