### ISSUE TITLE
I want to display the current month, last month, next month, is it possible ?

### ISSUE THREAD

**Issue by rahman9868** [Applandeo/Material-Calendar-View#255]
I want to display the full current month, full last month, full next month, but when I make it like this, 

`  val min = Calendar.getInstance()
        min.add(Calendar.MONTH, -1)
        val max = Calendar.getInstance()
        max.add(Calendar.MONTH, 1)
        calendarView.setMinimumDate(min)
        calendarView.setMaximumDate(max)`

I just get 1 month before today and 1 month after today

**Comment by kormateusz** [comment]
It is not the place to learn you programming!
