### ISSUE TITLE
How to remove divider line between vertical date on CalendarView like datepicker?

### ISSUE THREAD

**Issue by fnzainal** [Applandeo/Material-Calendar-View#256]
How to make custom layout CalendarView like datepicker?
-  remove divider line between vertical date
-  adjust margin vertical
-  and custom the selector date with drawable rounded box?
-  change day color column day ex: sunday with different color

![image](https://user-images.githubusercontent.com/13946213/71451839-5c085a00-27b0-11ea-9950-83c1e6727cae.png)
![image](https://user-images.githubusercontent.com/13946213/71451996-5b70c300-27b2-11ea-80f2-922c0e6f6c39.png)

**Comment by fabriciosomini** [comment]
I also need to know how to do this.

**Comment by kormateusz** [comment]
In new version there will be ability to customize days cells https://github.com/Applandeo/Material-Calendar-View/tree/develop#custom-view-for-days-cells
