### ISSUE TITLE
Issue with Data Binding

### ISSUE THREAD

**Issue by emreaydogdu** [Applandeo/Material-Calendar-View#261]
I cant set the Color for `app:selectionColor` with Data Binding. 
I try it with `app:selectionColor="@{calendarColor.color}"`  
but i get this Error

```
Cannot find a setter for <com.applandeo.materialcalendarview.CalendarView app:selectionColor> that accepts parameter type 'int'

If a binding adapter provides the setter, check that the adapter is annotated correctly and that the parameter type matches.
```

`@{calendarColor.color}` is an int value. 
How we can fix this or you can add `app:selectionColor` to set it programitacly.

**Comment by mateuszSawa** [comment]
You need to do custom binding. All information you have in error!

**Comment by emreaydogdu** [comment]
@mateuszSawa my Binding works. I can use this value for other usage. But if I want to use it for this parameter I get this error. I don't know why.
