### ISSUE TITLE
Make EventDay fields public so that we have more flexibility

### ISSUE THREAD

**Issue by giancarlogatti** [Applandeo/Material-Calendar-View#263]
I want to add an event as soon as the user clicks on the day on the calendar but the mDay variable for EventDay is private so I don't know what day I clicked on in the code, and also there's no function to set the drawable either.

**Comment by kormateusz** [comment]
https://www.w3schools.com/java/java_encapsulation.asp

**Comment by giancarlogatti** [comment]
I understand that but there's literally no method for setting a drawable resource for an existing EventDay object. And there's literally no reason why this can't be an open class, it just makes it so much more limited. Also what if I want to find out the day that EventDay is created with? How is this information that you must keep private, you can at least provide a getter for it.
