### ISSUE TITLE
Can we get implementation of equals and hashcode for EventDay?

### ISSUE THREAD

**Issue by giancarlogatti** [Applandeo/Material-Calendar-View#264]
I am storing my EventDay in a hashmap and when I compare to an EventDay upon OnDayPressed that is effectively the same (same values), but different memory addresses, it will return false for containing key in my hashmap because the library doesn't follow recommendation to implement equals and hashcode for the EventDay object. The class should be open, as in member fields should be protected

In short, can we get getters for the fields of EventDay and setters as well, as is common in Java. This will help the library be more extensible. Thank you.

**Comment by Afur** [comment]
Hello @giancarlogatti checkout our latest release `com.applandeo:material-calendar-view:1.8.0-rc01`
