### ISSUE TITLE
setSelectedDate

### ISSUE THREAD

**Issue by beingamitkumartiwari** [Applandeo/Material-Calendar-View#27]
Hi Dev Team,
You have provided a method calendarView.getSelectedDates(); for getting selected dates. 
but i want when any body open calendarView then they got some by default selected date.
 like calendarView.getSelectedDates(); you have any method for setSelectedDates();

**Comment by kormateusz** [comment]
Hi,

It will be implemented in version 1.4.1.

**Comment by shrpereira** [comment]
Is this feature available in some beta version? I really need it and I'll have to change my DatePicker library to delivery the feature I'm working  right now if it wasn't available.

**Comment by kormateusz** [comment]
Hi, added to version 1.5.0.
