### ISSUE TITLE
how to to select only one date in type="range_picker"

### ISSUE THREAD

**Issue by naveenclicklab** [Applandeo/Material-Calendar-View#276]
I want you select one date in "range_picker mode". its select other date not same 
e.g its working like  **ToDate** =6 feb **FormDate** =8 feb 
I want select **ToDate** =6 feb **FormDate** =6 feb. 
i didn't want to change the type="range_picker mode" rest fo thinks depending on it

**Comment by kormateusz** [comment]
![image](https://user-images.githubusercontent.com/2614225/73912291-6c821900-48b4-11ea-913c-e8962cb9e945.png)

I don't want to select one date in "range_picker" mode in your calendar 🤔
