### ISSUE TITLE
Refresh State Issue

### ISSUE THREAD

**Issue by Shantanuiyengar** [Applandeo/Material-Calendar-View#277]
If the code is set programmatically, the view doesnt refresh! Even though the functioanlity is available! 
Example:
calendar.setDisabledDays(disabled_dates2);
Calendar has the dates disabled as per the list but the view doesnt show any color change!

**Comment by mateuszSawa** [comment]
@Shantanuiyengar did you check documentation or source code how calendar it's working ?

**Comment by Shantanuiyengar** [comment]
Refresh state of the calendar isnt working!
