### ISSUE TITLE
setSelectedDates() not working anymore

### ISSUE THREAD

**Issue by rathesh77** [Applandeo/Material-Calendar-View#278]
i used to use this function to select dates programmatically but it stopped working for no reason. I tried to set the calendar to range_picker and many_days_picker but i can't make it work.

**Comment by rathesh77** [comment]
I have finally managed to find where the problem was by reading over a hundred times the readme files : Simply put List<Calendar> selectedDates = calendarView.getSelectedDates() then add calendar objects to that same array

**Comment by bluraygun** [comment]
> I have finally managed to find where the problem was by reading over a hundred times the readme files : Simply put List selectedDates = calendarView.getSelectedDates() then add calendar objects to that same array in order to add more dates to be selected. If you initialize a List with an empty ArrayList it won't work.

It doesn't work for me, it stops working. Can you reopen the issue?
