### ISSUE TITLE
Animation is too slow when chaning month and put events.

### ISSUE THREAD

**Issue by butyear** [Applandeo/Material-Calendar-View#279]
Hi,

In my project, I want to show data for each date. (ex. some count by day)
When executing app, it shows data without any problem.
But when I swipe or change month, a lag occurs.
I guess `fun setEvents(eventDays: List<EventDay>)` updates data in calendar view and this is performed with swiping animation at the same time.

Here is simplified code, 
```
calendar_view.setOnPreviousPageChangeListener(listener = object : OnCalendarPageChangeListener
{
    override fun onChange() {
        eventList = .. get from DB
        calendar_view.setEvents(eventList)
    }
}) 
```
I also tried to put delay before `setEvent`, but it still has problem (a little bit better)
So, now I'm considering to load 6-12 month data at once for reducing the animation lag problem.
But I want to know if this is the best way in the current situation or not.

Thanks again for developing this useful library.

**Comment by Afur** [comment]
@butyear I think you should create some caching for your events. In your scenario the animation is slow because calendar has to render events for new page each time when you're changing page.
