### ISSUE TITLE
setOnDayClickListener is not executing

### ISSUE THREAD

**Issue by ZakiResoluteSolutions** [Applandeo/Material-Calendar-View#28]
setOnDayClickListener is not executing in version 1.3.2 and I am not using app:datePicker="true" in xml. What is the problem?

my xml code looks like below:

```
**<com.applandeo.materialcalendarview.CalendarView
        android:id="@+id/calendarview_picker"
        android:layout_width="match_parent"
        android:layout_height="380dp"
        app:headerColor="@color/lightBlue"
        app:type="one_day_picker"
        app:datePicker="false"
        android:divider="@android:color/transparent"
        app:selectionColor="@color/colorAccent"
        app:todayLabelColor="@color/colorPrimaryDark" />**
```

**Note:** I am using this in Dialog. When i debug my app and click on date setOnDayClickListener is not executing. Please help. My code is below:

```
final CalendarView calendarview_picker = (CalendarView) dialog.findViewById(R.id.calendarview_picker);
            calendarview_picker.setOnDayClickListener(new OnDayClickListener() {
                public Date start_date,end_date;
                @Override
                public void onDayClick(EventDay eventDay) {
                    int size = calendarview_picker.getSelectedDates().size();
                    start_date = eventDay.getCalendar().getTime();
                }
            });
```

**Comment by ZakiResoluteSolutions** [comment]
@kormateusz please help me as soon as possible on this issue.

**Comment by kormateusz** [comment]
Hi, 
Please remove `app:datePicker` from your xml code because it is deprecated.
Do you want to use calendar as a picker whether a classic calendar?

**Comment by ZakiResoluteSolutions** [comment]
I want to use range picker. I also try after removing `app:datePicker` but no change.

**Comment by kormateusz** [comment]
So, why did you set "app:type="one_day_picker"? You have to set "range_picker" -> [https://github.com/Applandeo/Material-Calendar-View#customization](https://github.com/Applandeo/Material-Calendar-View#customization)

And I think, this is the answer to your question -> [https://github.com/Applandeo/Material-Calendar-View/issues/2](https://github.com/Applandeo/Material-Calendar-View/issues/2)

**Comment by ZakiResoluteSolutions** [comment]
```
<com.applandeo.materialcalendarview.CalendarView
        android:id="@+id/calendarview_picker"
        android:layout_width="match_parent"
        android:layout_height="380dp"
        app:headerColor="@color/lightBlue"
        app:type="range_picker"
        android:divider="@android:color/transparent"
        app:selectionColor="@color/colorAccent"
        app:todayLabelColor="@color/colorPrimaryDark" />
```

my updated code is here. But still setOnDayClickListener is not executing. Is there a problem while using this in dialog?

**Comment by ZakiResoluteSolutions** [comment]
Please help me @kormateusz

**Comment by mateuszSawa** [comment]
@ZakiResoluteSolutions Hi, please check our : [answer](https://github.com/Applandeo/Material-Calendar-View/issues/2)

**Comment by ZakiResoluteSolutions** [comment]
@kormateusz I do it as shown in this issue #2 but still setOnDayClickListener is not executing. 

This is my xml:

```
<com.applandeo.materialcalendarview.CalendarView
        android:id="@+id/calendarview_picker"
        android:layout_width="match_parent"
        android:layout_height="380dp"
        app:headerColor="@color/lightBlue"
        app:type="range_picker"
        android:divider="@android:color/transparent"
        app:selectionColor="@color/colorAccent"
        app:todayLabelColor="@color/colorPrimaryDark" />
```

And this is my code:

 ```
public class ViewDialog {

        public void showDialog(Activity activity, String msg) {
            final Dialog dialog = new Dialog(activity,android.R.style.Theme_Light);
            dialog.requestWindowFeature(Window.FEATURE_NO_TITLE);
            dialog.setCancelable(false);
            dialog.setContentView(R.layout.change_date_layout);

final CalendarView calendarview_picker = (CalendarView) dialog.findViewById(R.id.calendarview_picker);
            calendarview_picker.setOnDayClickListener(new OnDayClickListener() {
                public Date start_date,end_date;
                @Override
                public void onDayClick(EventDay eventDay) {
                    int size = calendarview_picker.getSelectedDates().size();
                    start_date = eventDay.getCalendar().getTime();
                }
            });

 dialog.show();

        }
    }
```

And I am calling this function like this:

```
ViewDialog alert = new ViewDialog();
alert.showDialog(MyActivity.this, "");
```

Now guide me what i am doing wrong here? My setOnDayClickListener is not executing.

**Comment by ZakiResoluteSolutions** [comment]
@mateuszSawa @kormateusz  Please guide me

**Comment by kormateusz** [comment]
Have you read whole issue?

> That's why it's not working. OnDayClickListener is only available in calendar mode, not in date picker mode. In date picker mode user can select a day and then you can get selected day using getSelectedDate() method.

**Comment by ZakiResoluteSolutions** [comment]
@kormateusz but i am not using date picker mode. 

```
<com.applandeo.materialcalendarview.CalendarView
        android:id="@+id/calendarview_picker"
        android:layout_width="match_parent"
        android:layout_height="380dp"
        app:headerColor="@color/lightBlue"
        app:type="range_picker"
        android:divider="@android:color/transparent"
        app:selectionColor="@color/colorAccent"
        app:todayLabelColor="@color/colorPrimaryDark" />
```

see this. Hope you understand now

**Comment by ZakiResoluteSolutions** [comment]
So I don't get click event of dates in range_picker? any solution for this? I need on click event of day, So i have to perform some action on it

**Comment by kormateusz** [comment]
In the current version, you don't.

**Comment by ZakiResoluteSolutions** [comment]
how can i know that the date is clicked or select so i can call getSelectedDate() method? Is anything possible for this? I have TextView of StartDate and EndDate and when user select dates range i have to display StartDate and EndDate in TextView without clicking any button. Hope you understand now what i want. Is this possible to do with your library? Please help

**Comment by ZakiResoluteSolutions** [comment]
So how can i set round background on date in calendar when the date is selected while using app:type="classic"? I need to set background color of selected date and I also what 2 date selection for StartDate and EndDate. Is it possible? Please help me for this

**Comment by ZakiResoluteSolutions** [comment]
![simulator screen shot nov 30 2017 7 10 46 pm](https://user-images.githubusercontent.com/34500827/34203256-6f9f8fce-e5a0-11e7-991d-ef2b14d99da8.png)

See this image, I need two date to be select. Hope you understand what i want. Please help me on this. How can i achieve this

**Comment by ZakiResoluteSolutions** [comment]
Any possibility @kormateusz @mateuszSawa ?

**Comment by ZakiResoluteSolutions** [comment]
How you change the background color when date is selected without any event? Please help me on this? I want click event of date in range_picker. @kormateusz @mateuszSawa
