### ISSUE TITLE
Set previous and forward button drawable in xml bug

### ISSUE THREAD

**Issue by AngelDamyanov** [Applandeo/Material-Calendar-View#282]
Can't set drawables for previous and forward button from xml. Works programmatically
<img width="513" alt="Screenshot 2020-02-20 at 9 59 17" src="https://user-images.githubusercontent.com/51187070/74912625-b516f780-53c7-11ea-96b8-a8e8142bd306.png">

**Comment by kormateusz** [comment]
Hi, which version you are using?

**Comment by AngelDamyanov** [comment]
Hi, I am using 'com.applandeo:material-calendar-view:1.8.0-rc01'

**Comment by kormateusz** [comment]
Please try 1.7.0

**Comment by AngelDamyanov** [comment]
Still can't

**Comment by kormateusz** [comment]
Could you show me your code?

**Comment by AngelDamyanov** [comment]
Version
`implementation 'com.applandeo:material-calendar-view:1.8.0-rc01'`

XML
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/spinner_dropdown"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@drawable/round_corners_white"
    android:orientation="vertical">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="horizontal"
        android:layout_marginEnd="20dp"
        android:layout_marginStart="20dp"
        android:layout_marginTop="20dp"
        android:layout_marginBottom="11dp">

        <TextView
            android:id="@+id/title_textView"
            android:layout_width="0dp"
            android:layout_height="30dp"
            android:layout_weight="1"
            android:gravity="start|center_vertical"
            android:textSize="13sp"
            android:fontFamily="@font/manrope_extrabold"

            app:layout_constraintBottom_toBottomOf="@+id/cross"
            app:layout_constraintEnd_toStartOf="@+id/cross"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent" />

        <ImageView
            android:id="@+id/cross"
            android:layout_width="30dp"
            android:layout_height="30dp"
            android:maxHeight="40dp"
            android:src="@drawable/ic_cross"
            android:tint="@color/grey"
            android:layout_gravity="center_vertical"

            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toEndOf="@+id/spinner_textView"
            app:layout_constraintTop_toTopOf="parent" />
    </LinearLayout>

    <com.applandeo.materialcalendarview.CalendarView
        android:id="@+id/calendarView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="8dp"
        app:headerColor="@color/white"
        app:headerLabelColor="@color/dark_blue"
        app:selectionColor="@color/blue_lighter"
        app:type="one_day_picker"
        android:minHeight="200dp"/>


</LinearLayout>`

Code
`fun Activity.calendarDropdownMenu(
    textTitle: String,
    disabledDays: List<Calendar>,
    v: View,
    preselected: Calendar?
) {
    val displayMetrics = this.resources.displayMetrics
    val displayHeight = displayMetrics.heightPixels
    val density = displayMetrics.density


    val root = findViewById<ConstraintLayout>(R.id.root_view)
    0.5f.applyDim(root)

    val inflater = getSystemService(Context.LAYOUT_INFLATER_SERVICE) as LayoutInflater
    val popupView = inflater.inflate(R.layout.calendar_dropdown, root, false)

    val width = LinearLayout.LayoutParams.MATCH_PARENT
    val height = (900 * density * 0.5f).toInt()//(displayHeight / 2)
    val focusable = true

    val popupWindow = PopupWindow(popupView, width, height, focusable)
    val textView = popupView.findViewById<TextView>(R.id.title_textView)
    textView.text = textTitle

    val calendar = popupView.findViewById<CalendarView>(R.id.calendarView)
    calendar.setPreviousButtonImage(getDrawable(R.drawable.ic_chevron_left_black)!!)
    calendar.setForwardButtonImage(getDrawable(R.drawable.ic_chevron_right_black)!!)
    calendar.setDisabledDays(disabledDays)
    calendar.setMinimumDate(Calendar.getInstance())
    calendar.setMaximumDate(Calendar.getInstance().also { it.add(Calendar.MONTH, 2) })
    if (preselected != null) {
        calendar.setDate(preselected)
    }

    val myFormat = "dd-MM-yyyy"
    val sdf = SimpleDateFormat(myFormat, Locale.UK)

    val slideIn = Slide()
    slideIn.slideEdge = Gravity.BOTTOM
    popupWindow.enterTransition = slideIn

    val slideOut = Slide()
    slideOut.slideEdge = Gravity.BOTTOM
    popupWindow.exitTransition = slideOut

    popupWindow.showAtLocation(root, Gravity.BOTTOM, 0, 0)

    popupWindow.setOnDismissListener { clearDim(root) }
    popupView.findViewById<ImageView>(R.id.cross).setOnClickListener { popupWindow.dismiss() }

    popupView.findViewById<CalendarView>(R.id.calendarView).setOnDayClickListener(object :
        OnDayClickListener {
        override fun onDayClick(eventDay: EventDay) {
            val clickedDayCalendar = eventDay.calendar
            val timeAsString = sdf.format(clickedDayCalendar.time)
            e("TIME_AS_STRING", timeAsString)
            if (eventDay.calendar.before(Calendar.getInstance().also {
                    it.add(
                        Calendar.MONTH,
                        2
                    )
                })) {
                if (eventDay.calendar.after(Calendar.getInstance())) {
                    e("TIME_VALIDATED", timeAsString)
                    (v as TextInputEditText).setText(timeAsString, TextView.BufferType.EDITABLE)
                    popupWindow.dismiss()
                }
            }

        }
    })
}`

Programatically it works, but when i try in xml the drawables aren't available. Tried cleaning and rebuilding the project. Doesn't work.
Tried: ``implementation 'com.applandeo:material-calendar-view:1.7.0'`` - doesn't work

**Comment by kormateusz** [comment]
Paste:
app:previousButtonSrc="@drawable/ic_chevron_left_black"
app:forwardButtonSrc="@drawable/ic_chevron_right_black"

**Comment by AngelDamyanov** [comment]
It works when you paste the full address
