### ISSUE TITLE
How change date background color programmatically

### ISSUE THREAD

**Issue by TMuhammed** [Applandeo/Material-Calendar-View#296]
Hello how change date background color programmatically like this 
https://user-images.githubusercontent.com/2614225/34562842-709a71ee-f150-11e7-966b-cbbe6169b88b.png

help please

**Comment by kormateusz** [comment]
https://github.com/Applandeo/Material-Calendar-View#customization-1

**Comment by kaulex99** [comment]
This only works for the picker, is there a possibility for the CalendarView too? I can't find one (in XML it is app:pagesColor="[color]". Any similar method?
