### ISSUE TITLE
How to add events from Retrofit

### ISSUE THREAD

**Issue by FajriSruntulan** [Applandeo/Material-Calendar-View#301]
I use json data, which attribute value of tanggal_absen used to add events.

`"data": [
        {
            "id": 5992,
            "siswa_id": 28,
            "tanggal_absen": "2020-04-01",
            "jam_masuk": null,
            "jam_pulang": null,
            "keterangan": "Alpha",
            "deleted_at": null,
            "created_at": "2020-04-24 10:12:00",
            "updated_at": "2020-04-24 10:12:00"
        },
        {
            "id": 6844,
            "siswa_id": 28,
            "tanggal_absen": "2020-04-02",
            "jam_masuk": null,
            "jam_pulang": null,
            "keterangan": "Sakit",
            "deleted_at": null,
            "created_at": "2020-04-24 10:12:01",
            "updated_at": "2020-04-24 10:12:01"
        },`

**Comment by mateuszSawa** [comment]
Not connected with our library.

**Comment by FajriSruntulan** [comment]
> Not connected with our library.


can enter the Array value in this code calendar.add(Calendar.DAY_OF_MONTH,1);

**Comment by kormateusz** [comment]
no
