### ISSUE TITLE
How can i disable past dates in this library?

### ISSUE THREAD

**Issue by VedGaur2045** [Applandeo/Material-Calendar-View#306]
I want to do work on this calendar but i can't disable and color change of past dates from current date.
So help me , How can i do.

**Comment by AleArmengol** [comment]
You can achieve this by doing: 

        //get the current date
        Date currentDate = Calendar.getInstance().getTime(); 
        
        //Convert Date to Calendar
        Calendar currentDateCalendar = Calendar.getInstance();  
        currentDateCalendar.setTime(currentDate);

        //Set minimum date
        calendarView.setMinimumDate(currentDateCalendar);
