### ISSUE TITLE
CalendarView in activity layout its taking more time to load the activity.

### ISSUE THREAD

**Issue by NagenBiswal** [Applandeo/Material-Calendar-View#308]
If i am using this com.applandeo.materialcalendarview.CalendarView in activity layout its taking more time to load. whay this so time ??? if it ts doing some task then it shoud not block the other ui component. Can you plz help me?

**Comment by fernandohkuku** [comment]
I have the same problem, I thought it could be the leaks of my application, but I managed to eliminate absolutely all the leaks.
---------------------------------------------------------------------
 0 APPLICATION LEAKS
    
    References underlined with "~~~" are likely causes.
    Learn more at https://squ.re/leaks.
    ====================================
    0 LIBRARY LEAKS
    
    A Library Leak is a leak caused by a known bug in 3rd party code that you do not have control over.
    See https://square.github.io/leakcanary/fundamentals-how-leakcanary-works/#4-categorizing-leaks
------------------------------------------------------------------------
if i remove the calendar the activity open fast but when i add the calendar view is slow. i don't know what is the problem and i don't have much elements view in my layout, if is the first time is so slow.

**Comment by sathamkhussain** [comment]
I'm facing thes Same issue.
