### ISSUE TITLE
Efficiency is not good with fragments

### ISSUE THREAD

**Issue by iNuman** [Applandeo/Material-Calendar-View#312]
1. It creates a pause to load the calendar in fragment and event label color is not working. Is this is an issue or anyone had implemented event label color?

2. Secondly, Since today is 6th month of 2020 but when I pass 2020,6,3 to the calendar it's displaying this date in May as may is 5th month of 2020

**Comment by Afur** [comment]
@iNuman Can you provide sample code for issues that you raised?

**Comment by venkat20390** [comment]
Even i am facing the slow loading issue on fragments. Just the calendar view inside a constraint layout and fragment cause slow loading of the fragments

**Comment by Sahana312** [comment]
Facing same issue of efficiency with fragments. I have placed the calendar in the bottom sheet. When we load 10 years calendar, the bottom sheet opens very slowly and the transition from one month to other becomes very slow

**Comment by Sahana312** [comment]
@kormateusz - any suggestions for the above lagging issue?

**Comment by mateuszSawa** [comment]
@venkat20390 @Sahana312 Could you provide sample?

**Comment by iNuman** [comment]
@Sahana312 We can solve this my making our own custom calendar which will only load the previous and current month not future months which will make the efficiency better.
