### ISSUE TITLE
minimum and maximum date not working.

### ISSUE THREAD

**Issue by makwanagopalmech** [Applandeo/Material-Calendar-View#314]
When I set maximum and minimum date then it does not work programmatically.

**Comment by mateuszSawa** [comment]
Add code sample

**Comment by makwanagopalmech** [comment]
val pastDays: String =
            SharedPreferences.getValue(ConstantVariables.LEAVE_BACK_DAYS, "35").toString()
        val calenderMin = Calendar.getInstance()
        calenderMin.add(Calendar.DAY_OF_YEAR, -(pastDays.toInt()))
        val futureDays: String =
            SharedPreferences.getValue(ConstantVariables.LEAVE_FUTURE_DAYS, "91").toString()
        val calenderMax = Calendar.getInstance()
        calenderMax.add(Calendar.DAY_OF_YEAR, futureDays.toInt())
        rangeCalendarView.setMinimumDate(calenderMin)
        rangeCalendarView.setMaximumDate(calenderMax)
