### ISSUE TITLE
Setting headerColor to transparent is not working

### ISSUE THREAD

**Issue by only-a-bitwise** [Applandeo/Material-Calendar-View#315]
Setting the headerColor property to `@android:color/transparent` has no effect on the header color, although setting it to "normal" colors works fine.

**Comment by Afur** [comment]
Hi @only-a-bitwise I believe that you want to hide header. Am I correct?

**Comment by only-a-bitwise** [comment]
If by header you mean just the bar then yes. I want the text and the arrows to stay visible.

**Comment by Afur** [comment]
Currently it's not possible but you can add that and submit PR
