### ISSUE TITLE
Impossible to unselect previous selected date 

### ISSUE THREAD

**Issue by christianderrico** [Applandeo/Material-Calendar-View#316]
I'm trying to build a calendar view in order to select the dates where it has been inserted an appointment, but I want to refresh the calendar view after shaking the phone.
It's possible to clean the selected dates list in same way?

**Comment by Afur** [comment]
Hi @christianderrico 

Could you add steps to reproduce on our side what you want to achieve?

**Comment by christianderrico** [comment]
Thank you very much for your time @Afur, i've just solved asking two times calendarview.setSelectedDates(): one time i've got a list of all events and they're shown on the calendar view, then selection is removed after calling again calendarview.setSelectedDates() with an empty list.
