### ISSUE TITLE
set color to date

### ISSUE THREAD

**Issue by VivekPagar** [Applandeo/Material-Calendar-View#32]
If we add some event to a particular day ,then how to set color to that day instead of icon or text..?

**Comment by kormateusz** [comment]
Hi :)

Currently it's impossible but you can download our code and implement it yourself if you need such functionality.

**Comment by VivekPagar** [comment]
Hi
Thanks for your consideration
and i will look forword.

Best Regards
Vivek Pagar
Phn.9423422882
