### ISSUE TITLE
multiple events with differrent text icons in single day 

### ISSUE THREAD

**Issue by giovenice** [Applandeo/Material-Calendar-View#321]
hi, i saw in one of the RM's pic that there were multiple events with different icons in a single day.
i tried but it doesn't work, just the first one is showed

**Comment by Afur** [comment]
@giovenice Hello
Take a look at our sample project. We've created custom drawable for that scenario.
https://github.com/Applandeo/Material-Calendar-View/blob/d382f6a819334853ca498e7731d544ac229da755/sample/src/main/java/com/applandeo/materialcalendarsampleapp/CalendarActivity.java#L46
