### ISSUE TITLE
daysLabelsColor not working

### ISSUE THREAD

**Issue by EpariNigam** [Applandeo/Material-Calendar-View#326]
I tried using the library for `CalendarView`. Most of the features working great. But, **daysLabelsColor** is not working.

**Comment by Afur** [comment]
@EpariNigam Hello
Compare your code with our sample project. Here you can find how we're using **daysLabelsColor** property
https://github.com/Applandeo/Material-Calendar-View/blob/d382f6a819334853ca498e7731d544ac229da755/sample/src/main/java/com/applandeo/materialcalendarsampleapp/MainActivity.java#L131
