### ISSUE TITLE
How can I set different color of circular background to different dates in calendar

### ISSUE THREAD

**Issue by hellosagar** [Applandeo/Material-Calendar-View#327]
How can I set the different color of the circular background to different dates in the calendar
Please help thanks I want something like this
![image](https://user-images.githubusercontent.com/50016799/93918295-bd525f00-fd29-11ea-8936-91c39f98867a.png)

**Comment by kormateusz** [comment]
Hi, you can use version `1.9.0-alpha10` and pass list of `CalendarDay`s objects to `CalendarView`.

**Comment by hellosagar** [comment]
ok let me try with that

**Comment by hellosagar** [comment]
@kormateusz but how can set the circular to that particular date?

**Comment by kormateusz** [comment]
Just create xml's Drawable and set it as `backgroundResource` in `CalendarDay`.

https://github.com/Applandeo/Material-Calendar-View/blob/incorrect_render_for_normal_days/library/src/main/java/com/applandeo/materialcalendarview/CalendarDay.kt

**Comment by hellosagar** [comment]
@kormateusz thanks for helping me out
with that, I get the circular shape as a background of the date
but there is one bug that I spot that when I try to create a ```CalendarDay ``` object with this snippet code
```
val cal = Calendar.getInstance()
val calendarDay = CalendarDay(cal)
cd.selectedLabelColor = R.color.white
cd.backgroundResource = R.drawable.bg_event_dat_highlight
```
that is giving me this result 
![image](https://user-images.githubusercontent.com/50016799/94232500-c444c180-ff23-11ea-8828-deb47cfb0681.png)
Which is fine Im okay with it but when I try to change the date of the calendar before passing it to the CalendarDay object it is not working
for example this code snippet
```
val cal = Calendar.getInstance()
cal.set(2020,9,20)
val calendarDay = CalendarDay(cal)
cd.selectedLabelColor = R.color.white
cd.backgroundResource = R.drawable.bg_event_dat_highlight
```
this is not working then it is giving me no result
![image](https://user-images.githubusercontent.com/50016799/94232742-49c87180-ff24-11ea-9af9-5aeca56160fe.png)

as I want to pass the different date with a different color to the list of CalendarDay but it's not  working
Please help me out either Im doing something wrong or is this a bug?

**Comment by hellosagar** [comment]
I tried with this code snippet also
But still now working
```
            val sdf = SimpleDateFormat("dd-MM-yyyy");
            val date = sdf.parse("${i}-10-2020")
            val  cal = Calendar.getInstance()
            cal.time = date


            val asd = CalendarDay(cal)
            asd.selectedLabelColor = R.color.white
            asd.backgroundResource = R.drawable.bg_event_dat_highlight

            calendarDaysList.add(asd)
```
