### ISSUE TITLE
get all events from a single day

### ISSUE THREAD

**Issue by chemo-baza** [Applandeo/Material-Calendar-View#328]
Hi!

Is there any way I can grab all the events when I do click on a specific day?

Example:

calendarView.setOnDayClickListener(new OnDayClickListener() {
            @Override
            public void onDayClick(EventDay eventDay) {
//Grab all the list events here
            }
        });

**Comment by fernandohkuku** [comment]
I think I had already answered your question, 
if you want to get a list it's easy, you just have to create an event list in your custom event

![carbon (1)](https://user-images.githubusercontent.com/69286553/95539817-fab71d80-09b4-11eb-9ef0-8d6fba5f378b.png)

![carbon (4)](https://user-images.githubusercontent.com/69286553/95539908-36ea7e00-09b5-11eb-8e5b-f95a956e5979.png)

**Comment by chemo-baza** [comment]
> I think I had already answered your question,
> if you want to get a list it's easy, you just have to create an event list in your custom event
> 
> ![carbon (1)](https://user-images.githubusercontent.com/69286553/95539817-fab71d80-09b4-11eb-9ef0-8d6fba5f378b.png)
> 
> ![carbon (4)](https://user-images.githubusercontent.com/69286553/95539908-36ea7e00-09b5-11eb-8e5b-f95a956e5979.png)

Yes man, thanks so much for your example. I already used your example in my app and is working like a charm. Appreciate it!
