### ISSUE TITLE
Refresh calendar view after change disable dates

### ISSUE THREAD

**Issue by hzqabdullah** [Applandeo/Material-Calendar-View#329]
After I change the month using page change listener, it will call the API and return as a set of data that will be used to update the disabled days. My problem is that disabled days got to update its data but the calendar view hasn't updated its view. Can you help me to solve this issue?

**Comment by Afur** [comment]
@hzqabdullah Hello, please provide sample code

**Comment by ravithoria** [comment]
Same issue here,

For example, In November its work with API that disable date,
but while swipe right or click on right arrow, In December date disable color not working

Is there any properties which work programming side? (setDisabledDaysLabelsColor)
