### ISSUE TITLE
How to change day's background?

### ISSUE THREAD

**Issue by vastenitz** [Applandeo/Material-Calendar-View#330]
I want to change the background of all days of the calendar. So, how to do it?

**Comment by AhmedElsayedTaha** [comment]
I want also to know hot to change a specific days background

**Comment by Afur** [comment]
@vastenitz https://github.com/Applandeo/Material-Calendar-View#customization

@AhmedElsayedTaha You can create event for that day. 
More on that https://github.com/Applandeo/Material-Calendar-View#adding-events-with-icons
