### ISSUE TITLE
 Calendar is not showing dates whle opening for the first time

### ISSUE THREAD

**Issue by Sathyan-Elangovan** [Applandeo/Material-Calendar-View#332]
While opening the activity, the calendar is not showing the dates.But it shows Year,Month(First tow lines of view). After clicking the forward button it shows the next month dates.Then If i go back to current month it showing the dates.

**Comment by kormateusz** [comment]
Temporary try to use older version of `androidx.constraintlayout:constraintlayout` , for example '1.1.3' should works. That bug will be fixed in next version.

**Comment by Sathyan-Elangovan** [comment]
When will we get the next release?

**Comment by edward1988** [comment]
@Sathyan-Elangovan hi,  i had a similar issue. Try to use relative layout as main container for calendar view. It works for me.

**Comment by Sathyan-Elangovan** [comment]
@edward1988 Okay.I will try with Relative layout.

**Comment by fabriciosomini** [comment]
I'm also experiencing a similar issue, when using the Standard Calendar, I'm not seeing the days, only the header.
It started happening after upgrading ConstraintLayout to 2.0.2.

**Comment by Afur** [comment]
@Sathyan-Elangovan @fabriciosomini Set `android:layout_width="0dp"` instead of `android:layout_width="match_parent"`

```
<androidx.constraintlayout.widget.ConstraintLayout
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.applandeo.materialcalendarview.CalendarView
        android:id="@+id/calendarView"
        android:layout_width="0dp"  <------------- here
        android:layout_height="wrap_content"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        />

</androidx.constraintlayout.widget.ConstraintLayout>
```
