### ISSUE TITLE
highlight day issue

### ISSUE THREAD

**Issue by hassanrana** [Applandeo/Material-Calendar-View#340]
when i select a ddate it gets highlighted but when i change my selection previous date doesn't unlighted..Please help

**Comment by kormateusz** [comment]
Please show your code.

**Comment by hassanrana** [comment]
calendarView.setOnDayClickListener(new OnDayClickListener() {
                        @Override
                        public void onDayClick(EventDay eventDay) {
                            tv_chooseDate.setVisibility(View.GONE);
                            Calendar clickedDayCalendar = eventDay.getCalendar();
                            //List<Calendar> calendars = new ArrayList<>();
                            //calendars.add(clickedDayCalendar);
                            //calendarView.setHighlightedDays(calendars);
                            try {
                                setAdapter(clickedDayCalendar.getTime().getTime());
                            } catch (ParseException e) {
                                e.printStackTrace();
                            }
                        }
                    });

**Comment by Afur** [comment]
@hassanrana Could you send us more accurate code sample? This one above doesn't reproduce your issue
