### ISSUE TITLE
How do I add mutiple icons to a single event?

### ISSUE THREAD

**Issue by ijustarrived** [Applandeo/Material-Calendar-View#343]
In one of the examples of the read me there's an image that has mutiple icons on a single day. I'm guessing that's with the eventday list. I have a list with multiple event items on the same date with different cions and I only see the icon of the 1st event. Lets say I want to have 2 icons on monday. I add two to eventday items with the same date(monday), but different icons. When I run it, I only see the icons of the 1st eventday

**Comment by kormateusz** [comment]
Hi,

Please, check out our same app. If you want to show 2 or more icons you have to do it yourself using xml like in this example:

https://github.com/Applandeo/Material-Calendar-View/blob/master/sample/src/main/res/drawable/sample_four_icons.xml

or by creating drawable programmatically similarly to this example:

https://github.com/Applandeo/Material-Calendar-View/blob/master/sample/src/main/java/com/applandeo/materialcalendarsampleapp/utils/DrawableUtils.java

**Comment by ijustarrived** [comment]
So I can't dynamically insert multiple icons? I have to have them predefined into an xml and then use that an icon
