### ISSUE TITLE
How To Set Event in Single Picker Calendar

### ISSUE THREAD

**Issue by habeeb1303** [Applandeo/Material-Calendar-View#35]
How To Set Event in type=Single Picker Calendar

**Comment by kormateusz** [comment]
Hi, in current version it's not possible ;)

**Comment by habeeb1303** [comment]
then update it

**Comment by mateuszSawa** [comment]
@habeeb1303 this is open source project. If you want help us, feel free to send pull request with this functionality!

**Comment by kormateusz** [comment]
Hi, added to version 1.5.0.
