### ISSUE TITLE
Having trouble adding events.

### ISSUE THREAD

**Issue by zfreiter** [Applandeo/Material-Calendar-View#355]
I'm trying to set events to appear when the Calendar is first opened with the code below.  I've tried different things but haven't had any luck.  When I use setOnDayClickListener, I can have events with a drawable added to the calendar view.  I would really like to have the events show on start.  Is there something I am doing wrong.  I am using implementation 'com.applandeo:material-calendar-view:1.7.0'.

var testArray: ArrayList<EventDay> = ArrayList()
        
val testCalendar = Calendar.getInstance()
testArray.add(EventDay(testCalendar, R.drawable.sample_circle))
mCalendarView.setEvents(testArray)

**Comment by kormateusz** [comment]
https://github.com/Applandeo/Material-Calendar-View/blob/master/sample/src/main/java/com/applandeo/materialcalendarsampleapp/CalendarActivity.java

**Comment by zfreiter** [comment]
Thank you.
