### ISSUE TITLE
setOnDayClickListener not working

### ISSUE THREAD

**Issue by Oumaima-abm** [Applandeo/Material-Calendar-View#357]
calendarView.setOnDayClickListener(new OnDayClickListener() {
    @Override
    public void onDayClick(EventDay eventDay) {
        Calendar clickedDayCalendar = eventDay.getCalendar();    
print(clickedDayCalendar)
    }
});
Is not working for me. Same goes with the LongClick one, there's no error shown in the logcat or anything, when i click on a day it simply does nothing

**Comment by kormateusz** [comment]
What version of the library you used? Could you send more accurate code sample?

**Comment by Oumaima-abm** [comment]
here is the version that i'm using : `implementation` 'com.applandeo:material-calendar-view:1.9.0-rc03'``
So what i'm trying to do i have scheduled reminders, and when the Day with an event is clicked on, i want the app to show me what the note contains (I tried to make a new class las shown in your website where i implement eventday with a note but it didn't work it was telling me the EventDay type is Final so icouldn't inherit from it)
Here is the code that i'm trying but nothing is done
event the print dont get executed
`` calendarView.setOnDayClickListener(object : OnDayClickListener {
            override fun onDayClick(eventDay: EventDay) {
                val clickedDayCalendar = eventDay.calendar
                print(clickedDayCalendar)
                for (i in 0..listnotes.size - 1) {
                    print(listnotes[i].reminderdate)
                    print(clickedDayCalendar.time.toString())
                    if (listnotes[i].reminderdate == clickedDayCalendar.time.toString()) {
                        print("hahahahah")
                        note.text = listnotes[i].description
                    }
                }

            }
        })``
