### ISSUE TITLE
How to add multiple events at single date? 

### ISSUE THREAD

**Issue by MohammadAliK** [Applandeo/Material-Calendar-View#358]
How do I add multiple event's in single date?. and how do I manage custom UI for event background with text.

For example:
![image](https://user-images.githubusercontent.com/35557476/106701826-366a9880-65df-11eb-9810-8cdd499ae9f3.png)

**Comment by Oumaima-abm** [comment]
Just a question, did you get towork with setOndayClickListener ? Is it working for you? 
And yes I do need as well to be able to add multiple events on the same day

**Comment by kormateusz** [comment]
It's impossible to add multiple events to single date. EventDay class only let you set a specific icon to a specific date. If you want to store something in EventDay class you have to extend it like in this article: https://applandeo.com/blog/material-calendar-view-customized-calendar-widget-android/

If you want to achieve event icon like in your example you have to create such Drawable object and pass it to EventDay.

**Comment by utkarshgupta4jan** [comment]
@kormateusz But EventDay class is final so it can't be inherited.
