### ISSUE TITLE
Clear calendar

### ISSUE THREAD

**Issue by matheusaguiardev** [Applandeo/Material-Calendar-View#36]
How can I clear the selected days? (With a clean button) and how can i scroll to today month ?

**Comment by kormateusz** [comment]
Hi,

Clearing isn't currently implemented. To scroll to current date use [that method](https://github.com/Applandeo/Material-Calendar-View#setting-a-current-date).

Mateusz

**Comment by theblaizen** [comment]
I found a solution, but you should be careful with it. Still waiting for author add it into release...

Kotlin:
`
fragmentManager
            ?.beginTransaction()
            ?.detach(this)
            ?.attach(this)
            ?.commit()
`

**Comment by avik-capitalnumbers** [comment]
Can you please implement the clearSelection() function for this library.it will be helpful for me. thanks in adv.

**Comment by avik-capitalnumbers** [comment]
i found the solution, try it hope it will work fine.
**implement this method on this java class-CalendarView.java**
 public void clearSelectedDates() {
        mCalendarProperties.clearDays();
        mCalendarPageAdapter.notifyDataSetChanged();
    }

**implement this method on this java class-CalendarProperties**
  public void clearDays() {
        if(mSelectedDays!=null) {
            mSelectedDays.clear();
        }
    }

**implement this method on this java class-DayRowClickListener**

   private void selectOneDay(View view, Calendar day) {
        List<SelectedDay> selectedDays = mCalendarPageAdapter.getSelectedDays();

        SelectedDay previousSelectedDay=null;

        if (selectedDays.isEmpty()) {

            Log.d("Size","----------------empty");

            TextView dayLabel = (TextView) view.findViewById(R.id.dayLabel);

            selectDay(dayLabel, day);
        } else
            previousSelectedDay = mCalendarPageAdapter.getSelectedDay();

        TextView dayLabel = (TextView) view.findViewById(R.id.dayLabel);

        if (isAnotherDaySelected(previousSelectedDay, day)) {
            selectDay(dayLabel, day);
            reverseUnselectedColor(previousSelectedDay);
        }
    }
