### ISSUE TITLE
Migrate to Maven Central

### ISSUE THREAD

**Issue by Didier116** [Applandeo/Material-Calendar-View#363]
JFrog just announced that they'll be shutting down JCenter:
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Key dates are:
    February 28th: No more submissions will be accepted to Bintray, JCenter
    February 1st 2022: Bintray, JCenter services will no longer be available

Can you consider Material-Calendar-View switching to another maven repository like Maven central ?

**Comment by x-sheep** [comment]
Android Studio is now displaying a suggestion to remove `jcenter()` from the Gradle files.

**Comment by kormateusz** [comment]
Duplicated: https://github.com/Applandeo/Material-Calendar-View/issues/415

**Comment by pavlomelnyk** [comment]
It is now available on MavenCenter.
