### ISSUE TITLE
Add different icon or mark to different type of events

### ISSUE THREAD

**Issue by nilayp799** [Applandeo/Material-Calendar-View#368]
i have two types of events let trueEvents and falseEvents, so i want to add different mark to both type of dates.
if i first set trueEvents using calenderview.setEvents(trueEvents), then i use same for falseEvents. i can only set trueEvents falseEvents are not reflected even after setEvent!

**Comment by sourav-android** [comment]
I am facing the same issue. I want to show two different icons for respective dates, but only one is shown.

**Comment by kormateusz** [comment]
Lib doesn't support multiple events per one day. The only way to have two icons in one day is to pass combined drawable to EventDay. https://github.com/Applandeo/Material-Calendar-View#adding-events-with-icons
