### ISSUE TITLE
Couldn't select the current Day?

### ISSUE THREAD

**Issue by varunchandran333** [Applandeo/Material-Calendar-View#372]
The "OK" button is disabled when we select the current date.
![image](https://user-images.githubusercontent.com/24404413/112477497-14002a80-8d99-11eb-85b1-797324639ac8.png)

**Comment by kormateusz** [comment]
Which version?

**Comment by varunchandran333** [comment]
implementation 'com.applandeo:material-calendar-view:1.7.0'

**Comment by varunchandran333** [comment]
![calendarIssue](https://user-images.githubusercontent.com/24404413/112480362-f5e7f980-8d9b-11eb-99c1-a45f7baf98a8.gif)

**Comment by kormateusz** [comment]
Please try `com.applandeo:material-calendar-view:1.9.0-rc03` and let me know if the issue still exists.

**Comment by varunchandran333** [comment]
The issue doesn't exist in this version, "OK" button is always enabled.
