### ISSUE TITLE
Range date picker bug

### ISSUE THREAD

**Issue by NKosyanchuk** [Applandeo/Material-Calendar-View#373]
Hello, faced with the UI issue.
I am using 1.7 version

Simple setup the range date picker and if you select two dates starting and ending in different weeks, you can see that the date selection is not happened for all the dates. 

![Screenshot 2021-03-26 at 13 51 01](https://user-images.githubusercontent.com/8013212/112627524-69d8df00-8e3a-11eb-91b4-719e126ce684.png)
![Screenshot 2021-03-26 at 13 50 14](https://user-images.githubusercontent.com/8013212/112627538-6cd3cf80-8e3a-11eb-9a4d-a287213d59e1.png)

**Comment by AngelDamyanov** [comment]
Did you find a way to fix this

**Comment by kormateusz** [comment]
Fixes in 1.9.0-rc04
