### ISSUE TITLE
Is it possible to set day color once event has been added to specific day

### ISSUE THREAD

**Issue by grzegorzpnk** [Applandeo/Material-Calendar-View#374]
I'd like to set a color for a specific date ( the same way as it is changing during selection) once event has been created.
Is it possible or should I implement it on my own?

**Comment by grzegorzpnk** [comment]
@kormateusz @mateuszSawa

**Comment by kormateusz** [comment]
https://github.com/Applandeo/Material-Calendar-View#customization-of-specific-cells
