### ISSUE TITLE
Could I set a 2 letter month name? 

### ISSUE THREAD

**Issue by Orange1353** [Applandeo/Material-Calendar-View#377]
In my string resources I have set what I want, but it doesn't work:

![image](https://user-images.githubusercontent.com/40850831/113321992-d5301e80-931c-11eb-86a6-109a8b986b7c.png)

![image](https://user-images.githubusercontent.com/40850831/113321618-72d71e00-931c-11eb-9edd-a228fcc62b41.png)

I love this library, and only this little detail stayed for me

I use 1.9.0-rc03

**Comment by kormateusz** [comment]
Cannot replicate.
