### ISSUE TITLE
For all events we need to create separate calendar class object. 

### ISSUE THREAD

**Issue by karatelamusman** [Applandeo/Material-Calendar-View#38]
```
eventDays.add(new MyEvent(c2, R.mipmap.ic_launcher));        
c2.add(Calendar.DATE,5);
eventDays.add(new MyEvent(c2, R.mipmap.ic_launcher));
```
above code add only one event inside list....why?

**Comment by mateuszSawa** [comment]
@karatelamusman it's not issue connected with our calendar. Your code is incorrect.

**Comment by karatelamusman** [comment]
Then what should i do to add multiple events for different date. And keeping track of all and later retrieve when it is requested...

Kindly help me..
