### ISSUE TITLE
error duplicate value for resource 'attr/type' with config ''

### ISSUE THREAD

**Issue by milanmaji** [Applandeo/Material-Calendar-View#383]
When use [this](https://github.com/Applandeo/Material-Calendar-View)  library and [Mercadopago](https://github.com/mercadopago/px-android)  library both in same project  below error occurred.
error: duplicate value for resource 'attr/type' with config ' '.

**Comment by mateuszSawa** [comment]
@milanmaji did you report [them()](https://github.com/mercadopago/px-android) issue?

**Comment by milanmaji** [comment]
Yes but no reply received.
