### ISSUE TITLE
Feature - Ability to change only month and/or only year (with a spinner)

### ISSUE THREAD

**Issue by Brice155** [Applandeo/Material-Calendar-View#395]
Hello !

Your calendar view is awsome and exactly what i needed ! Just for that, thanks a lot !!!
I think that it would be great to just select the month or just the year.
For example, in my application, sometimes i want to select a very old date (i.e. 1995-08-12) and just using the previous button can take a long time :)

Best regards.

Brice

**Comment by kormateusz** [comment]
If you use: https://github.com/Applandeo/Material-Calendar-View#setting-a-current-date it will move calendar to your date :)
