### ISSUE TITLE
jcenter is at it's end of life.

### ISSUE THREAD

**Issue by dj1993cse** [Applandeo/Material-Calendar-View#397]
any update or plan on moving to a different repository.

**Comment by MichalStranik** [comment]
JCenter service update

JFrog, the company that maintains the JCenter artifact repository used by many Android projects, made JCenter a read-only repository on March 31st, 2021. According to the announcement, JCenter will allow downloads of existing artifacts indefinitely.

Developers who publish artifacts on JCenter should migrate their packages to a new host, such as Maven Central.

Developers who use dependencies from JCenter will need to find the new location of updated versions of those dependencies.

**Comment by kormateusz** [comment]
Duplicated: https://github.com/Applandeo/Material-Calendar-View/issues/415

**Comment by pavlomelnyk** [comment]
It is now available on MavenCenter.
