### ISSUE TITLE
How to highlight current date with custom background drawable?

### ISSUE THREAD

**Issue by Pradeepkumar2091** [Applandeo/Material-Calendar-View#403]
Hello Dev,
Thanks for this wonderful library.

I am facing an issue, i want to highlight current date with custom background drawable. could you please anyone tell me how can i achieve this. 

Check below image, i want to add background color on i.e. **7**.

![Screenshot_1631022778_copy](https://user-images.githubusercontent.com/17064383/132357473-055d7b7b-1364-4906-99a5-a761c4e35225.png)

**Comment by kormateusz** [comment]
You can use CalendarDay: https://github.com/Applandeo/Material-Calendar-View#customization-of-specific-cells
