### ISSUE TITLE
Remove next month days from current month

### ISSUE THREAD

**Issue by ansh94** [Applandeo/Material-Calendar-View#41]
Hi,
Is there a way to not show the next month days in the current month?. For eg some days of February are shown at the end of January.

**Comment by bendder21** [comment]
First of all, sorry for my English. Try to add this (dayLabel.setTextColor(Color.TRANSPARENT);) in method setLabelColors (CalendarDayAdapter.java) inside condition: if (!isCurrentMonthDay(day)) {}
This is the final method implementation (works for me):

private void setLabelColors(TextView dayLabel, Calendar day) {
        // Setting not current month day color
        if (!isCurrentMonthDay(day)) {

            DayColorsUtils.setDayColors(dayLabel, mCalendarProperties.getAnotherMonthsDaysLabelsColor(),
                    Typeface.NORMAL, R.drawable.background_transparent);
                  //hidden next month days            
                 dayLabel.setTextColor(Color.TRANSPARENT);

            return;
        }

        // Set view for all SelectedDays
        if (isSelectedDay(day)) {
            Stream.of(mCalendarPageAdapter.getSelectedDays())
                    .filter(selectedDay -> selectedDay.getCalendar().equals(day))
                    .findFirst().ifPresent(selectedDay -> selectedDay.setView(dayLabel));

            DayColorsUtils.setSelectedDayColors(dayLabel, mCalendarProperties);
            return;
        }

        // Setting disabled days color
        if (!isActiveDay(day)) {
            DayColorsUtils.setDayColors(dayLabel, mCalendarProperties.getDisabledDaysLabelsColor(),
                    Typeface.NORMAL, R.drawable.background_transparent);
            return;
        }

        // Setting current month day color
        DayColorsUtils.setCurrentMonthDayColors(day, mToday, dayLabel, mCalendarProperties);
    }

**Comment by kormateusz** [comment]
Set transparent color in app:anotherMonthsDaysLabelsColor="[color]".

**Comment by bendder21** [comment]
Ok! Sorry!!

**Comment by kormateusz** [comment]
So, simply use the same color as your background has.
