### ISSUE TITLE
how to highlight the disabled date on click of the date? 

### ISSUE THREAD

**Issue by shruthitechm** [Applandeo/Material-Calendar-View#413]
We have highlighted the date with a red circle if the date is enabled  and clicked. 
How can we do it for disabled dates(ones in yellow)? I want to highlight when disabled date is clicke
![device-2021-11-10-164915](https://user-images.githubusercontent.com/78098871/141104432-adfe47b0-33aa-48b0-9a7a-f0d2485a8e64.png)
d.

**Comment by kormateusz** [comment]
You can use CalendarDay https://github.com/Applandeo/Material-Calendar-View#customization-of-specific-cells
