### ISSUE TITLE
PLEASE CHANGE TO MAVENCENTRAL PLEASE

### ISSUE THREAD

**Issue by turtlee** [Applandeo/Material-Calendar-View#415]
Guys can you please change this library to MavenCentral.. JCenter is going down we need to update our projects..

**Comment by ticherhaz** [comment]
Any update about changing to MavenCentral?

**Comment by pavlomelnyk** [comment]
It is now available on MavenCenter.

**Comment by NikShuvalov** [comment]
Can I request for version 1.7 to be available on MavenCentral? I'm only seeing the latest release Candidate on MavenCentral and I'm facing the issues outlined in https://github.com/Applandeo/Material-Calendar-View/issues/401. It would be nice to be able to downgrade the version to quickly resolve it
