### ISSUE TITLE
Can I configure the number of rows of the calendar. I now see 6 rows, can i make it 5 rows?

### ISSUE THREAD

**Issue by shruthitechm** [Applandeo/Material-Calendar-View#428]

**Comment by mtrakal** [comment]
Not a good idea, because some months require 6 rows to show all days, in that case content under calendar will jumping or you will loose days 30/31 in calendar :)

![image](https://user-images.githubusercontent.com/1458891/171391672-7b780895-d381-4a4d-8a2a-5733be8d902a.png)

**Comment by kormateusz** [comment]
No, it's impossible.
