### ISSUE TITLE
Change from Jcenter to MavenCentral

### ISSUE THREAD

**Issue by 4l3xand3r** [Applandeo/Material-Calendar-View#436]
A change to MavenCenter will soon be nessessary as any projects needing jcenter as a dependency won't be able to upgrade the AGP to 8.0 which is an issue.

![grafik](https://user-images.githubusercontent.com/44643285/191511286-a6a43e33-2c9e-4087-b5b0-d551dc511fb8.png)

**Comment by NikShuvalov** [comment]
Can I request for version 1.7 to be available on MavenCentral? I'm only seeing the latest release Candidate on MavenCentral and I'm facing the issues outlined in https://github.com/Applandeo/Material-Calendar-View/issues/401. It would be nice to be able to downgrade the version to quickly resolve it
