### ISSUE TITLE
DateUtils.getCalendar not working

### ISSUE THREAD

**Issue by charrieanne** [Applandeo/Material-Calendar-View#453]
the
![getCalendar](https://github.com/Applandeo/Material-Calendar-View/assets/75109852/3d8ad11e-d0ab-4b06-b07c-0b9959c59695)
 getCalendar has a line stroke is it not available anymore? im trying to set the disabled dates which are the weekends

**Comment by kormateusz** [comment]
It's still working. It's just deprecated. Use `DateUtils.getMidnightCalendar()` instead
