### ISSUE TITLE
Disable day click

### ISSUE THREAD

**Issue by snDavidPozo** [Applandeo/Material-Calendar-View#460]
Hi,
We are currently using your calendar in our project and we have encountered an error that causes the app to crash. This is caused when we have a full month disabled and try to click on any day. Attached error trace. We need to solve the problem urgently, since we were planning to use this component in several projects.

![Captura de pantalla 2024-03-25 a las 10 31 07 a  m](https://github.com/Applandeo/Material-Calendar-View/assets/99198704/768fe658-9324-4836-9af8-b18e69ce4442)

![Captura de pantalla 2024-03-25 a las 10 24 56 a  m](https://github.com/Applandeo/Material-Calendar-View/assets/99198704/ac89d0c4-bdfd-4407-9b03-a50003f9ce8f)

**Comment by PawelPalacz1** [comment]
Hi. Sure. We will try to allocate sbd to check this issue.

**Comment by snDavidPozo** [comment]
Good afternoon, 
We continue to increase the number of errors caused by the bug in the calendar. 

![Captura de pantalla 2024-03-27 a las 13 04 20 p  m](https://github.com/Applandeo/Material-Calendar-View/assets/99198704/aea8fb4a-d964-4930-ae66-4020333e5e6c)

Is there any progress? Is there a possibility to catch such an error so that at least it does not throw such an exception?
Thanks for your attention.

**Comment by kormateusz** [comment]
Hi, could you please attach the full calendar configuration?

**Comment by pavlomelnyk** [comment]
@snDavidPozo we are testing a fix. The new release will probably be today. @kormateusz will update

**Comment by kormateusz** [comment]
@snDavidPozo new version 1.9.1 is available on maven :) please let us know if fixes resolve your issue :)

**Comment by snDavidPozo** [comment]
Good morning, 
We have just tested version 1.9.1 and the bug has been successfully fixed. 
Thank you very much for the quick solution!

**Comment by snDavidPozo** [comment]
Resolved
