### ISSUE TITLE
Add and remove even on setOnDayClickListener does not giving disable state

### ISSUE THREAD

**Issue by kingnightdrifter** [Applandeo/Material-Calendar-View#47]
Hello there,

i wanted to know how to get active and de-active state of daySelectedListener? I want to date in arraylist on day click and remove date when re-tab on day. in this regard i am using bellow code

DateFormat formatter = new SimpleDateFormat("EEE MMM dd HH:mm:ss Z yyyy", Locale.US);
                DateFormat newFormate = new SimpleDateFormat("yyyy-MM-dd");
                Date dt;
                try {
                    dt = formatter.parse(str);
                    System.out.println("Time Display: " + newFormate.format(dt));
                    String finalTime = newFormate.format(dt);
                    if(eventDay.isEnabled()) {
                        arrayList.add(finalTime);
                        Toast.makeText(getContext(),finalTime,Toast.LENGTH_SHORT).show();
                    }
                    else
                    {
                        Toast.makeText(getContext(),"Removed",Toast.LENGTH_SHORT).show();
                    }

                    // <-- I got result here
                } catch (ParseException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }

   if(eventDay.isEnabled()) 
this code only gives one state not giving the state if day already have been selected...
Please help

**Comment by kormateusz** [comment]
The `isEnabled()` method only informs whether a day is enabled or disabled, it doesn't tell you whether a day is "selected".
