### ISSUE TITLE
How to prevent swipe to next or previous month

### ISSUE THREAD

**Issue by kingnightdrifter** [Applandeo/Material-Calendar-View#48]
Hello there,
I want to prevent horizontal scrolling for changing month but could not get any property or don't get any solution in this regard.
Your help will be appreciated. thanks

**Comment by mateuszSawa** [comment]
@kingnightdrifter there is no possibility to block scrolling.

**Comment by kingnightdrifter** [comment]
@mateuszSawa any other posibility to block this. i dont want to permit user to change or scrol next month

**Comment by kormateusz** [comment]
@kingnightdrifter Set min date to first day of the month and the max date to the last day of the month.

**Comment by kingnightdrifter** [comment]
@kormateusz is it possible dynamically

**Comment by kormateusz** [comment]
Try.

**Comment by kingnightdrifter** [comment]
@kormateusz any suggestion plz.
I am trying to  calendarView.setMinimumDate(Calendar.getInstance());

**Comment by kormateusz** [comment]
...and? Yes it's a method to set a minimum date.

**Comment by kingnightdrifter** [comment]
@kormateusz what should be the method to set maximum date? and what param me have to passed on that

**Comment by kormateusz** [comment]
Where did you find setMinimumDate method?

**Comment by kingnightdrifter** [comment]
ok i under stand but i wanted to know what should passed in setMinimumDate  and setMaximumDate

**Comment by kingnightdrifter** [comment]
ok I got the Answer By this Way...

 Calendar calendar = Calendar.getInstance();
        Calendar calendar12 = Calendar.getInstance();
        calendar.set(Calendar.DAY_OF_MONTH,calendar.getActualMinimum(Calendar.DAY_OF_MONTH));
        calendar12.set(Calendar.DAY_OF_MONTH,calendar12.getActualMaximum(Calendar.DAY_OF_MONTH));
        calendarView.setMinimumDate(calendar);
        calendarView.setMaximumDate(calendar12);
