### ISSUE TITLE
Failed to find GeneratedAppGlideModule. You should include an annotationProcessor compile dependency on com.github.bumptech.glide:compiler in your application and a @GlideModule annotated AppGlideModule implementation or LibraryGlideModules will be silently ignored

### ISSUE THREAD

**Issue by anudroid91** [Applandeo/Material-Calendar-View#54]
Getting this warning every time I try to add an event to CalendarView. Maybe because of this I am not able to add an event to it.

Code Snippet :-

        Calendar event = Calendar.getInstance();
        event.set(2018, 2, 13);
        List<EventDay> events = new ArrayList<>();
        events.add(new EventDay(event, R.drawable.add_button_selector));

        calendarView.showCurrentMonthPage();
        calendarView.setMinimumDate(calFrom);
        calendarView.setMaximumDate(calTo);
        calendarView.setEvents(events);
        calendarView.setVisibility(View.VISIBLE);

**Comment by kormateusz** [comment]
Hi, do you use Glide library in your project? Try to update it or change version to **4.3.0** (this one is used in our library).
