### ISSUE TITLE
Problem with version 1.4.0 and Glide 4.6.1. Are there any solution?

### ISSUE THREAD

**Issue by yayoro** [Applandeo/Material-Calendar-View#58]
I have this problem. Are not compatible this libraries?

Im using last version of Glide (4.6.1) and last version of MaterialCalendarView (1.4.0)

Third imagen shows the error.

![captura de pantalla 2018-03-01 a las 21 47 22](https://user-images.githubusercontent.com/26386809/36871203-c0226410-1da1-11e8-8dc4-2de2ef89e564.png)
![captura de pantalla 2018-03-01 a las 21 46 47](https://user-images.githubusercontent.com/26386809/36871205-c26cf190-1da1-11e8-845a-092ec8a25de2.png)
![captura de pantalla 2018-03-01 a las 21 46 59](https://user-images.githubusercontent.com/26386809/36871209-c46e5344-1da1-11e8-9dd1-87e10746c65b.png)

Thanks so much guys!

**Comment by SamaludheenCignes** [comment]
@yayoro how did you solve this. I am facing the same issue

**Comment by loctra** [comment]
please add into proguard-rules
-dontwarn com.applandeo.materialcalendarview.utils.ImageUtils

**Comment by MbaiMburu** [comment]
not working after adding 
-dontwarn com.applandeo.materialcalendarview.utils.ImageUtils
in proguard
