### ISSUE TITLE
Scroll up and down in Calendar View to see all days in small screen device

### ISSUE THREAD

**Issue by yayoro** [Applandeo/Material-Calendar-View#59]
Is possible to make scroll in Calendar View to see all days where screen devices is very smaller??

Im working with Android 2.3.3 and Material Calendar View 1.4.0.

In next picture you can see how last days are hidden because view is smaller than Calendar View. Is possible make scroll??

![img_8979](https://user-images.githubusercontent.com/26386809/36943982-41aaf720-1f93-11e8-8273-0e1f47d369f1.png)

Thanks so much!

**Comment by brjichkar-ezest** [comment]
Same issue, I need to show calendar in small view on main layout. How to achieve it?

**Comment by kormateusz** [comment]
You can put your callendar to a ScrollView.
