### ISSUE TITLE
There is no default constructor available in com.applandeo.materialcalendarview.EventDay

### ISSUE THREAD

**Issue by andrewlaurien** [Applandeo/Material-Calendar-View#69]
Good Day,
I'm using your library for adding events and save it to firebase database. But when i change to another device and log in my credentials. The library throws the error when i parse the JSON data from firebase and pass it as MyEventDay(extends EventDay).

Sorry for if my issue is incomprehensible. Im not a native english speaker. Thanks

**Comment by mateuszSawa** [comment]
@andrewlaurien it's not issue connected with calendar library

**Comment by FarhanMuftiHilmy** [comment]
how can i get the default constructor
