### ISSUE TITLE
Allow adding multiple notes to same calendar day

### ISSUE THREAD

**Issue by shuwnyuantee** [Applandeo/Material-Calendar-View#74]
I am using `Material-Calendar-View` in my Note app. I need to add multiple notes to 1 calendar day. Notes are categorized into tags, which are represented with different colours. So I need to show multiple images on same calendar day, instead of single icon.

I have made code changes & here's the screenshot:

![device-2018-04-07-193127](https://user-images.githubusercontent.com/614382/38454488-e948c40e-3a9a-11e8-8099-74345825af4f.png)

Do you think this might benefit your project & any possibility to consider merging this feature in?

Here's my Pull Request:  https://github.com/Applandeo/Material-Calendar-View/pull/73

Feedbacks are most welcome. I can make whatever changes to suit the project's need :)

Really appreciate the great library, thanks! 👍

**Comment by sambhu815** [comment]
![](https://user-images.githubusercontent.com/614382/38454488-e948c40e-3a9a-11e8-8099-74345825af4f.png)

can i get the code for the multiple color dots on same date ?

**Comment by karthikslegend** [comment]
Hi, I need to add a single dot below a date, Please tell me how to do that or an example will also be fine? I have no idea.

**Comment by 111lomaz111** [comment]
@shuwnyuantee  hi how u change size of the icons on callendar?

**Comment by xyznaveen** [comment]
Can anyone tell me how to add the color indicator.

**Comment by 111lomaz111** [comment]
@xyznaveen what color indicator?
event logo?

**Comment by kormateusz** [comment]
Hi,

Thank you very much for your effort and your PR. In the version 1.5.0 we added an abbility to set any Drawable as event icon and that can be handled using new possibilities.
