### ISSUE TITLE
Delay in launching calendar view (from XML)

### ISSUE THREAD

**Issue by vinsbhat** [Applandeo/Material-Calendar-View#77]
I have added one day picker Calendar view to my dialog in xml. Whenever I launch the dialog following error is thrown. There is a considerable amount of delay between the time I clicked and the time it shows Calendar

logs:
I/AppCompatDelegate: The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's
I/Choreographer: Skipped 33 frames!  The application may be doing too much work on its main thread.

**Comment by nguyenthanhduy91** [comment]
@vinsbhat can you fix it?

**Comment by jvtMari** [comment]
My problem is when i click the button that load the fragment with this calendar, it has delay before load it.
1.5/2 seconds. Is it normal?.

**Comment by FidanBacaj** [comment]
I solved this problem by removed `<com.applandeo.materialcalendarview.CalendarView/>` form activity.xml and i declare only in controller like
` val calendarView : CalendarView = ...
CaconstraintLayoutView.addView(calendarView)`

**Comment by RobertoSolisGT** [comment]
@FidanBacaj can you upload a complete solution for Java?
im having troubles with the "Attributes" that should be pass to the "CalendarView" constructor.

![capture](https://user-images.githubusercontent.com/48660647/54500233-44767980-48e0-11e9-9e7f-95974e066a8b.png)
