### ISSUE TITLE
After multiple load Material-Calendar-View shows the wrong day icon.

### ISSUE THREAD

**Issue by assembleMHN** [Applandeo/Material-Calendar-View#80]
Hi.

I have debugged this issue for ages now, and can conclude that after multiple loads the calendar might show the wrong icon. I have 59 event days i load in to the calendar, they can have one of two icons.

In my activity i have a toggle functionality between two calendars "week" and "month", when i switch between these multiple times material calendar view will begin showing the wrong icons and at some point stop showing icons at all. I can recreate this very easy just by jumping from the week to the month calendar multiple times.

Everytime i change from month to week the fragment that holds the material calendar view gets destroyed and therefor its a complete fresh version that is failing. The eventdays im passing is hardcoded and cannot change, but i even debugged the calendar view adapter with a breakpoint in the seteventdays function and have concluded that the eventdays are correct, even dough the calendar shows the wrong icons and none at all. Something goes completely haywire when destroying and loading the calendar again.

Currently im in a state where the calendar view refuses to show any icons at all, even dough i pass 59 hardcoded eventdays to it.

This image shows the correct layout build from the eventdays:

![screen shot 2018-05-09 at 09 58 11](https://user-images.githubusercontent.com/30831333/39802873-8a13ca90-536f-11e8-8960-36eba91ce51e.png)

This image shows the error after i changed between "dag (day)" and "måned (month)" 4 times, as you can see the one row of icons changed, the eventdays are exactly the same (hardcoded) this is also verified in the "seteventdays" in CalendarView where i can see that the eventdays do indeed have the correct icon, but the calendar shows them wrong anyways.

![screen shot 2018-05-09 at 09 59 30](https://user-images.githubusercontent.com/30831333/39802923-af239cc0-536f-11e8-9587-f1210554d851.png)

Please help.

Best Regards
Morten

**Comment by assembleMHN** [comment]
I have debugged some more, and can see that in this function:

    private void loadIcon(ImageView dayIcon, Calendar day) {
        if (mCalendarProperties.getEventDays() == null || mCalendarProperties.getCalendarType() != CalendarView.CLASSIC) {
            dayIcon.setVisibility(View.GONE);
            return;
        }

        Stream.of(mCalendarProperties.getEventDays()).filter(eventDate ->
                eventDate.getCalendar().equals(day)).findFirst().executeIfPresent(eventDay -> {

            ImageUtils.loadResource(dayIcon, eventDay.getImageResource());

            // If a day doesn't belong to current month then image is transparent
            if (!isCurrentMonthDay(day) || !isActiveDay(day)) {
                dayIcon.setAlpha(0.12f);
            }

        });
    }

The icon ID (eventDay.getImageResource()) is correct, but the calendar is loading the wrong one and not the one returned by "eventDay.getImageResource()"

**Comment by assembleMHN** [comment]
Seems that my problem has been solved in Glide 4.4.0:

"Fixed a couple of cases where calling load(Bitmap) or load(Drawable) could cause Glide to re-use or recycle the given Bitmap or Drawable (cff4f2c)."

https://github.com/bumptech/glide/releases

**Comment by assembleMHN** [comment]
I forked the project, update glide to current version, implemented it in my project and the error is gone. I can therefore confirm that the error is in Glide and that updating the project to newest version of glide will solve this problem.

**Comment by karthikslegend** [comment]
Hi, I need to add a single dot below a date, Please tell me how to do that or an example will also be fine? I have no idea.

**Comment by lsaulcastro** [comment]
@karthikslegend I am trying to add some events with an icon and it does not work. Nothing happens underneath I leave the code!

Urgent help!

![image](https://user-images.githubusercontent.com/24308050/41476754-768ba144-7090-11e8-9ce4-12ecbccc5941.png)
![image](https://user-images.githubusercontent.com/24308050/41476765-7e010036-7090-11e8-9a96-c958681b3f93.png)

**Comment by assembleMHN** [comment]
The developer seems to not support this library anymore, i never got a answer to my question, i fixed it my self and are now running on a private branch to make sure that a update to this library wont break my own. Good luck fixing :)

**Comment by kormateusz** [comment]
We will make more tests and probably remove Glide in one of next release if calendar will be working without any issues. Thank you for your effort.
