### ISSUE TITLE
I want to display only current month dates. 

### ISSUE THREAD

**Issue by mayankzen123** [Applandeo/Material-Calendar-View#84]
![screenshot_2018-05-21-16-16-01 1](https://user-images.githubusercontent.com/13898670/40304232-7ba6b208-5d13-11e8-9691-5dac0dd372e5.png)

Not want to display other month dates at end

**Comment by karthikslegend** [comment]
Hi, I need to add a single dot below a date, Please tell me how to do that or an example will also be fine? I have no idea.

**Comment by mayankzen123** [comment]
@karthikslegend https://github.com/Applandeo/Material-Calendar-View#adding-events-with-icons

**Comment by lsaulcastro** [comment]
@karthikslegend, @mayankzen123  That not found for me, helpe
look this;


![image](https://user-images.githubusercontent.com/24308050/41476632-295f3c8c-7090-11e8-8a09-dca8a52c53fd.png)

![image](https://user-images.githubusercontent.com/24308050/41476646-32e13242-7090-11e8-8aac-53396118a0b7.png)

**Comment by kormateusz** [comment]
@mayankzen123 you have to set a app:anotherMonthsDaysLabelsColor="[color]" to transparent or the colour of your background.
