### ISSUE TITLE
Selected start & end both date how to shown in same dialog.

### ISSUE THREAD

**Issue by Jiks19** [Applandeo/Material-Calendar-View#88]
Hi, 

I'm used this library. all are good and easy.
But I need the in CalendarView.RANGE_PICKER.
I select from date that how to show same date as label in same dialog
And I select to date that time how to show same to date as label in same dialog

In simple language.

The date I select is displayed in the dialog. in CalendarView.RANGE_PICKER

**Comment by kormateusz** [comment]
I don't understand your english but probably it's impossible. You can download our code and adjust it to your requirements.
