### ISSUE TITLE
setEvents, not found helpme

### ISSUE THREAD

**Issue by lsaulcastro** [Applandeo/Material-Calendar-View#89]
I am trying to add some events with an icon and it does not work. Nothing happens underneath I leave the code!

Urgent help!

![image](https://user-images.githubusercontent.com/24308050/41474884-34f3fad8-708b-11e8-9de6-dd1b2729f2c3.png)

![image](https://user-images.githubusercontent.com/24308050/41474909-495d861a-708b-11e8-8d80-957ee198fb0a.png)

**Comment by kormateusz** [comment]
Please use our sample code to compare.
