### ISSUE TITLE
with Glide

### ISSUE THREAD

**Issue by KennethSS** [Applandeo/Material-Calendar-View#90]
No virtual method into(Landroid/widget/ImageView;)Lcom/bumptech/glide/request/target/Target; in class Lcom/bumptech/glide/RequestBuilder; or its super classes (declaration of 'com.bumptech.glide.Reque

that's no answer really , i will hope fixed it

**Comment by kormateusz** [comment]
It's the issue of the Glide library which our calendar contains. Please update glide library in your project or add dependencies to it into the gradle file.
