### ISSUE TITLE
Customize Range selection.

### ISSUE THREAD

**Issue by jayesh28589** [Applandeo/Material-Calendar-View#92]
Hello kormateusz,

I am making some customization in this library,
I want to high light first and last date with blue color and others date in between with light blue color.

I have done it for all other month, but it is not worked when I start from 1st Jan, 2018, I mean when I click on 1st Jan, 2018 as first element and whatever other date (i.e 19 Jan, 20 feb ... etc) as second element then it is display with light blue.

I put the log and I think there is problem in setting click event of 1st January, 2018.

It calls getView method and (isSelectedDay(day)) becomes true 41 times in CalendarDayAdapter although mCalendarPageAdapter.getSelectedDays() has only size = 1, (i.e. 1st Jan, 2018)

It adds same date 1st Jan, 2018 as 41 times in when we click in 1st Jan, 2018.

I searched on It, finally I found the issue, it cause when the month start from Monday.

Please help me to fix it.

Please see the attached screenshot.

![device-2018-06-22-154138](https://user-images.githubusercontent.com/4100414/41771563-31f6128c-7633-11e8-94ba-3c389e0b2ea1.png)
![device-2018-06-22-154207](https://user-images.githubusercontent.com/4100414/41771564-321f4d78-7633-11e8-81bc-f7bfca1c8f4b.png)

Thanks.

**Comment by kormateusz** [comment]
Thanks for report issue. We will try to fix it in the next release or if you already found the solution please let me know.
