### ISSUE TITLE
Loading too slow

### ISSUE THREAD

**Issue by perlics** [Applandeo/Material-Calendar-View#93]
Fragment with calendar in it loads too slowly, messes up the animation of the drawer closing out.

**Comment by SARASWATHYD** [comment]
calendar page loading too slow. 
https://app.intercom.io/a/apps/xhnn6n6y/inbox/inbox/unassigned/conversations/19587317391

**Comment by SARASWATHYD** [comment]
https://app.intercom.io/a/apps/xhnn6n6y/inbox/inbox/1782359/conversations/19312946500

**Comment by FidanBacaj** [comment]
I solved  this problem by  removed `<com.applandeo.materialcalendarview.CalendarView/>` form activity.xml  and i declare only in controller like 
` val calendarView : CalendarView = ...
 CaconstraintCalendarView.addView(calendarView)`

**Comment by jmcoder1** [comment]
> 
> 
> I solved this problem by removed `<com.applandeo.materialcalendarview.CalendarView/>` form activity.xml and i declare only in controller like
> ` val calendarView : CalendarView = ...
> 
> CaconstraintLayoutView.addView(calendarView)`

How to you do this with Java and not Kotlin

**Comment by RobertoSolisGT** [comment]
> I solved this problem by removed `<com.applandeo.materialcalendarview.CalendarView/>` form activity.xml and i declare only in controller like
> ` val calendarView : CalendarView = ...
> 
> CaconstraintLayoutView.addView(calendarView)`

How to you do this with Java and not Kotlin

**Comment by jmcoder1** [comment]
> 
> 
> > I solved this problem by removed `<com.applandeo.materialcalendarview.CalendarView/>` form activity.xml and i declare only in controller like
> > ` val calendarView : CalendarView = ...
> > CaconstraintLayoutView.addView(calendarView)`
> 
> How to you do this with Java and not Kotlin

Let me know if you also figure this out please.
