### ISSUE TITLE
Adding multiple event icon on same day

### ISSUE THREAD

**Issue by dimuthunsj** [Applandeo/Material-Calendar-View#94]
is it possible to add multiple event with different icon for same day.if it is not possible , how can i extends that functionality.
if anyone know that please drop it, i really want it for my app.

**Comment by dimuthunsj** [comment]
i'm new to android development and i tried it several times, but couldn't. 
so can you please share your sample code.
Thanks.

**Comment by perlics** [comment]
https://stackoverflow.com/questions/30344053/how-do-you-edit-a-dependency-external-library-in-android-studio

follow this, and after that, edit xml

here is my sample:

calendar_view_day.xml:
<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="60dp"
    android:layout_height="60dp"
    android:orientation="vertical">


    <View
        android:id="@+id/leftColorHolder"
        android:layout_width="30dp"
        android:layout_height="wrap_content"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintStart_toStartOf="parent" />

    <View
        android:id="@+id/rightColorHolder"
        android:layout_width="30dp"
        android:layout_height="60dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent" />

    <TextView
        android:id="@+id/dayLabel"
        android:layout_width="60dp"
        android:layout_height="30dp"
        android:gravity="center"
        android:textSize="14sp"
        app:layout_constraintTop_toBottomOf="@+id/divider" />

    <ImageView
        android:id="@+id/leftIcon"
        android:layout_width="16dp"
        android:layout_height="28dp"
        android:layout_gravity="center_horizontal"
        android:layout_marginBottom="8dp"
        android:layout_marginEnd="8dp"
        android:layout_marginLeft="8dp"
        android:layout_marginRight="8dp"
        android:layout_marginStart="8dp"
        android:contentDescription="@string/description"
        android:scaleType="centerInside"
        app:layout_constraintBottom_toBottomOf="@+id/leftColorHolder"
        app:layout_constraintEnd_toStartOf="@+id/rightColorHolder"
        app:layout_constraintStart_toStartOf="parent" />

    <ImageView
        android:id="@+id/middleIcon"
        android:layout_width="16dp"
        android:layout_height="28dp"
        android:layout_gravity="center_horizontal"
        android:layout_marginBottom="8dp"
        android:layout_marginEnd="2dp"
        android:layout_marginLeft="2dp"
        android:layout_marginRight="2dp"
        android:layout_marginStart="2dp"
        android:contentDescription="@string/description"
        android:scaleType="centerInside"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="@+id/dayLabel"
        app:layout_constraintStart_toStartOf="@+id/dayLabel" />

    <ImageView
        android:id="@+id/rightIcon"
        android:layout_width="16dp"
        android:layout_height="28dp"
        android:layout_gravity="center_horizontal"
        android:layout_marginBottom="8dp"
        android:layout_marginEnd="8dp"
        android:layout_marginLeft="8dp"
        android:layout_marginRight="8dp"
        android:layout_marginStart="8dp"
        android:contentDescription="@string/description"
        android:scaleType="centerInside"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="@+id/rightColorHolder" />


    <View
        android:id="@+id/divider"
        android:layout_width="match_parent"
        android:layout_height="0.5dp"
        android:layout_marginBottom="8dp"
        android:background="@color/nextMonthDayColor" />

</android.support.constraint.ConstraintLayout>

**Comment by dimuthunsj** [comment]
Thank you very much, i will follow that
