### ISSUE TITLE
Not able to view all the events in the calendar view

### ISSUE THREAD

**Issue by rituvarmag** [Applandeo/Material-Calendar-View#95]
I was trying to add few events to SQLite DB and retrieve the same for viewing. But I couldn't get the day icon on all eventdays. The icon is appearing only on the last added event day. Tried Logging the event days and shows all the saved days are logging.

Kindly help me on this

**Comment by rituvarmag** [comment]
Y you have closed my issue. Pls provide some suggestion.

**Comment by martirius** [comment]
@rituvarmag Had the same problem, the solution is to create a new Calender for every Event
