### ISSUE TITLE
Highlight pressed date

### ISSUE THREAD

**Issue by waseem786** [Applandeo/Material-Calendar-View#97]
Hi, 
Is there any way to Highlight or change the background color of last selected date. Today date background can change, but when I press another date I want to see it differently. 

Thanks

**Comment by kormateusz** [comment]
Hi, there is no way to change the background of today date. You can only change the background color of all selected days.

**Comment by waseem786** [comment]
No, I don't want to change today date, what I need is, when I press a date it need to be highlighted.
Does any feature available?
Or any way to do that?
